In [1]:
from google.colab import drive
drive.mount('/content/drive')

import os, zipfile, shutil
from pathlib import Path

WORK_DIR = Path("/content/uav_beam_tracking_replica")
DATA_DIR = WORK_DIR / "data"
CODE_DIR = WORK_DIR / "code"
OUT_DIR = WORK_DIR / "outputs"

for p in [WORK_DIR, DATA_DIR, CODE_DIR, OUT_DIR]:
    p.mkdir(parents=True, exist_ok=True)

print("WORK_DIR:", WORK_DIR)
print("DATA_DIR:", DATA_DIR)
print("CODE_DIR:", CODE_DIR)

Mounted at /content/drive
WORK_DIR: /content/uav_beam_tracking_replica
DATA_DIR: /content/uav_beam_tracking_replica/data
CODE_DIR: /content/uav_beam_tracking_replica/code

In [2]:
from pathlib import Path

# CHANGE THIS PATH based on your Drive location
DATASET_ZIP = Path("/content/drive/MyDrive/scenario23_dev_w_resources.zip")

print("Exists:", DATASET_ZIP.exists())
print("Path:", DATASET_ZIP)

Exists: True
Path: /content/drive/MyDrive/scenario23_dev_w_resources.zip

In [3]:
import zipfile, os
from pathlib import Path

EXTRACT_DIR = DATA_DIR / "scenario23"
EXTRACT_DIR.mkdir(parents=True, exist_ok=True)

if not any(EXTRACT_DIR.iterdir()):
    with zipfile.ZipFile(DATASET_ZIP, "r") as z:
        z.extractall(EXTRACT_DIR)
    print("Unzipped to:", EXTRACT_DIR)
else:
    print("Already extracted:", EXTRACT_DIR)

!find /content/uav_beam_tracking_replica/data/scenario23 -maxdepth 3 -type f | head -30

Unzipped to: /content/uav_beam_tracking_replica/data/scenario23
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/scenario23.csv

In [4]:
!pip install -q torch torchvision torchaudio
!pip install -q pandas numpy pillow pyyaml tqdm scikit-learn ultralytics

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 43.0 MB/s eta 0:00:00

In [5]:
import os
from pathlib import Path
import pandas as pd

root = Path("/content/uav_beam_tracking_replica/data/scenario23")

print("CSV files:")
csv_files = list(root.rglob("*.csv"))
for i, p in enumerate(csv_files):
    print(i, p)

print("\nImage samples:")
for ext in ["*.jpg", "*.jpeg", "*.png"]:
    imgs = list(root.rglob(ext))
    if imgs:
        print(ext, len(imgs), imgs[0])
        break

CSV files:
0 /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/scenario23.csv

Image samples:
*.jpg 11387 /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_2568_17_05_32.jpg

In [6]:
import pandas as pd

CSV_PATH = csv_files[0]
df = pd.read_csv(CSV_PATH)

print("CSV_PATH:", CSV_PATH)
print("Shape:", df.shape)
print("Columns:")
print(list(df.columns))

display(df.head())

CSV_PATH: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/scenario23.csv
Shape: (11387, 17)
Columns:
['index', 'unit1_rgb', 'unit1_pwr_60ghz', 'unit1_loc', 'unit2_loc', 'unit2_speed', 'unit2_altitude', 'unit2_distance', 'unit2_height', 'unit2_x-speed', 'unit2_y-speed', 'unit2_z-speed', 'unit2_pitch', 'unit2_roll', 'seq_index', 'time_stamp[UTC]', 'unit1_beam_index']

,index,unit1_rgb,unit1_pwr_60ghz,unit1_loc,unit2_loc,unit2_speed,unit2_altitude,unit2_distance,unit2_height,unit2_x-speed,unit2_y-speed,unit2_z-speed,unit2_pitch,unit2_roll,seq_index,time_stamp[UTC],unit1_beam_index
0,1,./unit1/camera_data/image_BS1_1_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_1.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_1.txt,./unit2/speed/speed_1.txt,./unit2/altitude/altitude_1.txt,./unit2/distance/distance_1.txt,./unit2/height/height_1.txt,./unit2/x_speed/x_speed_1.txt,./unit2/y_speed/y_speed_1.txt,./unit2/z_speed/z_speed_1.txt,./unit2/pitch/pitch_1.txt,./unit2/roll/roll_1.txt,1,['16-58-42-0'],43
1,2,./unit1/camera_data/image_BS1_2_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_2.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_2.txt,./unit2/speed/speed_2.txt,./unit2/altitude/altitude_2.txt,./unit2/distance/distance_2.txt,./unit2/height/height_2.txt,./unit2/x_speed/x_speed_2.txt,./unit2/y_speed/y_speed_2.txt,./unit2/z_speed/z_speed_2.txt,./unit2/pitch/pitch_2.txt,./unit2/roll/roll_2.txt,1,['16-58-42-142'],43
2,3,./unit1/camera_data/image_BS1_3_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_3.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_3.txt,./unit2/speed/speed_3.txt,./unit2/altitude/altitude_3.txt,./unit2/distance/distance_3.txt,./unit2/height/height_3.txt,./unit2/x_speed/x_speed_3.txt,./unit2/y_speed/y_speed_3.txt,./unit2/z_speed/z_speed_3.txt,./unit2/pitch/pitch_3.txt,./unit2/roll/roll_3.txt,1,['16-58-42-284'],43
3,4,./unit1/camera_data/image_BS1_4_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_4.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_4.txt,./unit2/speed/speed_4.txt,./unit2/altitude/altitude_4.txt,./unit2/distance/distance_4.txt,./unit2/height/height_4.txt,./unit2/x_speed/x_speed_4.txt,./unit2/y_speed/y_speed_4.txt,./unit2/z_speed/z_speed_4.txt,./unit2/pitch/pitch_4.txt,./unit2/roll/roll_4.txt,1,['16-58-42-426'],43
4,5,./unit1/camera_data/image_BS1_5_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_5.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_5.txt,./unit2/speed/speed_5.txt,./unit2/altitude/altitude_5.txt,./unit2/distance/distance_5.txt,./unit2/height/height_5.txt,./unit2/x_speed/x_speed_5.txt,./unit2/y_speed/y_speed_5.txt,./unit2/z_speed/z_speed_5.txt,./unit2/pitch/pitch_5.txt,./unit2/roll/roll_5.txt,1,['16-58-42-568'],39

In [7]:
cols = list(df.columns)

def find_cols(keywords):
    out = []
    for c in cols:
        low = c.lower()
        if any(k in low for k in keywords):
            out.append(c)
    return out

print("Possible image columns:", find_cols(["image", "img", "rgb", "camera"]))
print("Possible beam columns:", find_cols(["beam", "label", "index", "power"]))
print("Possible lat columns:", find_cols(["lat"]))
print("Possible lon columns:", find_cols(["lon", "lng", "long"]))
print("Possible episode columns:", find_cols(["episode", "scene", "unit", "run", "traj"]))

Possible image columns: ['unit1_rgb']
Possible beam columns: ['index', 'seq_index', 'unit1_beam_index']
Possible lat columns: []
Possible lon columns: []
Possible episode columns: ['unit1_rgb', 'unit1_pwr_60ghz', 'unit1_loc', 'unit2_loc', 'unit2_speed', 'unit2_altitude', 'unit2_distance', 'unit2_height', 'unit2_x-speed', 'unit2_y-speed', 'unit2_z-speed', 'unit2_pitch', 'unit2_roll', 'unit1_beam_index']

In [12]:
CONFIG = {
    "root": str(root),
    "csv_path": str(CSV_PATH),

    "image_col": "unit1_rgb",
    "label_col": "unit1_beam_index",
    "episode_col": "seq_index",

    "bs_loc_col": "unit1_loc",
    "uav_loc_col": "unit2_loc",

    "image_size": 256,
    "seq_len": 4,
    "codebook_size": 64,

    # DeepSense beam index usually 1..64 হলে True লাগবে
    "label_is_one_indexed": True,
}

print(CONFIG)

{'root': '/content/uav_beam_tracking_replica/data/scenario23', 'csv_path': '/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/scenario23.csv', 'image_col': 'unit1_rgb', 'label_col': 'unit1_beam_index', 'episode_col': 'seq_index', 'bs_loc_col': 'unit1_loc', 'uav_loc_col': 'unit2_loc', 'image_size': 256, 'seq_len': 4, 'codebook_size': 64, 'label_is_one_indexed': True}

In [28]:
from pathlib import Path
from typing import List, Tuple
from functools import lru_cache
import ast
import re
import numpy as np
import pandas as pd
from PIL import Image

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms


@lru_cache(maxsize=4)
def build_image_index(root_str):
    """
    Root er vitore sob image filename index kore.
    Direct path fail korle filename diye image khuje ber korbe.
    """
    root = Path(root_str)
    image_index = {}

    for ext in ["*.jpg", "*.jpeg", "*.png", "*.JPG", "*.JPEG", "*.PNG"]:
        for p in root.rglob(ext):
            image_index[p.name] = p

    print(f"Image index built from {root}: {len(image_index)} images found")
    return image_index


def auto_fix_root(root):
    """
    Correct dataset root detect kore.
    Correct root holo oi folder jekhane:
        unit1/camera_data
    exists.
    """
    root = Path(root)

    if (root / "unit1" / "camera_data").exists():
        return root

    jpgs = list(root.rglob("*.jpg"))

    if len(jpgs) == 0:
        return root

    first_img = jpgs[0]

    for parent in first_img.parents:
        if (parent / "unit1" / "camera_data").exists():
            return parent

    return root


def resolve_path(root: Path, value: str) -> Path:
    """
    Robust image resolver.

    CSV te image path:
        ./unit1/camera_data/image_xxx.jpg

    Tries:
    1. absolute path
    2. root / cleaned relative path
    3. filename search inside root
    """
    root = auto_fix_root(root)

    value = str(value).strip().replace("\\", "/")
    cleaned = value.replace("./", "")

    p = Path(value)

    if p.is_absolute() and p.exists():
        return p

    candidate = root / cleaned

    if candidate.exists():
        return candidate

    image_index = build_image_index(str(root))
    fname = Path(cleaned).name

    if fname in image_index:
        return image_index[fname]

    raise FileNotFoundError(
        f"\nImage not found!\n"
        f"CSV value: {value}\n"
        f"Root: {root}\n"
        f"Tried: {candidate}\n"
        f"Filename: {fname}\n"
    )


def parse_loc_value(x):
    """
    unit1_loc / unit2_loc parse kore x,y,z ber kore.

    Handles:
    '[x, y, z]'
    '(x, y, z)'
    'x,y,z'
    or string with numbers.
    """
    if isinstance(x, (list, tuple, np.ndarray)):
        vals = list(x)[:3]

        while len(vals) < 3:
            vals.append(0.0)

        return np.array(vals, dtype=np.float32)

    s = str(x).strip()

    try:
        val = ast.literal_eval(s)

        if isinstance(val, (list, tuple)):
            vals = list(val)[:3]

            while len(vals) < 3:
                vals.append(0.0)

            return np.array(vals, dtype=np.float32)

    except Exception:
        pass

    nums = re.findall(r"[-+]?\d*\.\d+|[-+]?\d+", s)
    nums = [float(v) for v in nums]

    if len(nums) >= 3:
        return np.array(nums[:3], dtype=np.float32)

    elif len(nums) == 2:
        return np.array([nums[0], nums[1], 0.0], dtype=np.float32)

    elif len(nums) == 1:
        return np.array([nums[0], 0.0, 0.0], dtype=np.float32)

    return np.array([0.0, 0.0, 0.0], dtype=np.float32)


class UAVBeamSequenceDataset(Dataset):
    """
    Paper-style UAV beam tracking dataset.

    Output:
        images: [T, 3, 256, 256]
        gps:    [T, 2]
        label:  scalar

    T = 4:
        t-3, t-2, t-1, t
    """

    def __init__(
        self,
        df: pd.DataFrame,
        root: str,
        image_col: str,
        label_col: str,
        gps_cols: Tuple[str, str],
        seq_indices: List[List[int]],
        image_size: int = 256,
        label_is_one_indexed: bool = True,
    ):
        self.df = df.reset_index(drop=True)
        self.root = auto_fix_root(Path(root))
        self.image_col = image_col
        self.label_col = label_col
        self.gps_cols = gps_cols
        self.seq_indices = seq_indices
        self.label_is_one_indexed = label_is_one_indexed

        self.transform = transforms.Compose([
            transforms.Resize((image_size, image_size)),
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225],
            ),
        ])

    def __len__(self):
        return len(self.seq_indices)

    def _load_image(self, row):
        img_path = resolve_path(self.root, row[self.image_col])
        img = Image.open(img_path).convert("RGB")
        return self.transform(img)

    def __getitem__(self, idx):
        ids = self.seq_indices[idx]
        rows = self.df.iloc[ids]

        images = torch.stack(
            [self._load_image(row) for _, row in rows.iterrows()],
            dim=0
        )  # [T, 3, H, W]

        gps = torch.tensor(
            rows.loc[:, list(self.gps_cols)].values,
            dtype=torch.float32
        )  # [T, 2]

        label = int(rows.iloc[-1][self.label_col])

        # CrossEntropyLoss needs labels 0..63
        # DeepSense beam index normally 1..64
        if self.label_is_one_indexed:
            label -= 1

        return images, gps, torch.tensor(label, dtype=torch.long)


def add_relative_gps_and_normalize(df, cfg, fit_stats=None):
    """
    CSV columns:
        unit1_loc = BS location
        unit2_loc = UAV location

    rel = unit2_loc - unit1_loc

    Model GPS branch expects B x 2,
    so we use relative x,y.
    """
    df = df.copy()

    bs_col = cfg["bs_loc_col"]
    uav_col = cfg["uav_loc_col"]

    bs_xyz = np.stack(df[bs_col].apply(parse_loc_value).values)
    uav_xyz = np.stack(df[uav_col].apply(parse_loc_value).values)

    rel_xyz = uav_xyz - bs_xyz

    df["rel_lat"] = rel_xyz[:, 0]
    df["rel_lon"] = rel_xyz[:, 1]

    cols = ["rel_lat", "rel_lon"]

    if fit_stats is None:
        fit_stats = {
            "min": df[cols].min(),
            "max": df[cols].max(),
        }

    denom = (fit_stats["max"] - fit_stats["min"]).replace(0, 1.0)

    df[cols] = (df[cols] - fit_stats["min"]) / denom
    df[cols] = df[cols].fillna(0.0)

    return df, fit_stats


def make_sequence_indices(df, seq_len=4, episode_col=None):
    """
    Consecutive sequence banay.
    seq_index thakle separate session/episode mix korbe na.
    """
    seqs = []

    if episode_col is not None and episode_col in df.columns:
        groups = [
            list(g)
            for g in df.groupby(episode_col, sort=False).indices.values()
        ]
    else:
        groups = [list(range(len(df)))]

    for g in groups:
        for start in range(0, len(g) - seq_len + 1):
            seqs.append(g[start:start + seq_len])

    return seqs


def split_df_sequential(df, train_ratio=0.7, val_ratio=0.2):
    """
    Strict sequential split by seq_index.

    Same seq_index/session will not be split across train/val/test.

    Split:
        first 70% seq_index -> train
        next 20% seq_index  -> val
        last 10% seq_index  -> test
    """

    if "seq_index" not in df.columns:
        print("WARNING: seq_index not found. Falling back to row-level sequential split.")

        n = len(df)
        n_train = int(n * train_ratio)
        n_val = int(n * val_ratio)

        train_df = df.iloc[:n_train].reset_index(drop=True)
        val_df = df.iloc[n_train:n_train + n_val].reset_index(drop=True)
        test_df = df.iloc[n_train + n_val:].reset_index(drop=True)

        return train_df, val_df, test_df

    seq_values = df["seq_index"].drop_duplicates().tolist()
    n_seq = len(seq_values)

    n_train_seq = int(n_seq * train_ratio)
    n_val_seq = int(n_seq * val_ratio)

    train_seq_values = seq_values[:n_train_seq]
    val_seq_values = seq_values[n_train_seq:n_train_seq + n_val_seq]
    test_seq_values = seq_values[n_train_seq + n_val_seq:]

    train_df = df[df["seq_index"].isin(train_seq_values)].reset_index(drop=True)
    val_df = df[df["seq_index"].isin(val_seq_values)].reset_index(drop=True)
    test_df = df[df["seq_index"].isin(test_seq_values)].reset_index(drop=True)

    print("Strict seq_index-level split:")
    print("Total seq_index:", n_seq)
    print("Train seq_index:", len(train_seq_values))
    print("Val seq_index:", len(val_seq_values))
    print("Test seq_index:", len(test_seq_values))

    print("\nRow counts:")
    print("Train rows:", len(train_df))
    print("Val rows:", len(val_df))
    print("Test rows:", len(test_df))

    # Safety check: no overlap
    train_set = set(train_df["seq_index"].unique())
    val_set = set(val_df["seq_index"].unique())
    test_set = set(test_df["seq_index"].unique())

    assert train_set.isdisjoint(val_set), "Train/Val seq_index overlap!"
    assert train_set.isdisjoint(test_set), "Train/Test seq_index overlap!"
    assert val_set.isdisjoint(test_set), "Val/Test seq_index overlap!"

    print("\nNo seq_index overlap between train/val/test.")

    return train_df, val_df, test_df


print("Cell loaded successfully.")

Cell loaded successfully.

dataloader build

In [29]:

CONFIG = {
    "root": str(root),
    "csv_path": str(CSV_PATH),

    "image_col": "unit1_rgb",
    "label_col": "unit1_beam_index",
    "episode_col": "seq_index",

    "bs_loc_col": "unit1_loc",
    "uav_loc_col": "unit2_loc",

    "image_size": 256,
    "seq_len": 4,
    "codebook_size": 64,

    # Auto-detect below
    "label_is_one_indexed": True,
}

# Auto-fix root so that root/unit1/camera_data exists
CONFIG["root"] = str(auto_fix_root(CONFIG["root"]))

print("CONFIG root:", CONFIG["root"])
print("CSV path:", CONFIG["csv_path"])



df = pd.read_csv(CONFIG["csv_path"])

print("\nData shape:", df.shape)
print("Columns:", list(df.columns))

required_cols = [
    CONFIG["image_col"],
    CONFIG["label_col"],
    CONFIG["episode_col"],
    CONFIG["bs_loc_col"],
    CONFIG["uav_loc_col"],
]

for col in required_cols:
    assert col in df.columns, f"Missing column: {col}"

print("\nRequired columns found.")



label_min = int(df[CONFIG["label_col"]].min())
label_max = int(df[CONFIG["label_col"]].max())

print("\nLabel min/max BEFORE conversion:")
print(label_min, label_max)

if label_min == 0:
    CONFIG["label_is_one_indexed"] = False
elif label_min == 1:
    CONFIG["label_is_one_indexed"] = True
else:
    print("WARNING: label min is neither 0 nor 1. Check label column manually.")

print("label_is_one_indexed:", CONFIG["label_is_one_indexed"])



sample_img_value = df.loc[0, CONFIG["image_col"]]
sample_img_path = resolve_path(Path(CONFIG["root"]), sample_img_value)

print("\nSample CSV image:", sample_img_value)
print("Resolved image path:", sample_img_path)
print("Image exists:", sample_img_path.exists())



train_df, val_df, test_df = split_df_sequential(
    df,
    train_ratio=0.7,
    val_ratio=0.2
)

print("\nSplit dataframe shapes:")
print("train_df:", train_df.shape)
print("val_df:", val_df.shape)
print("test_df:", test_df.shape)



train_df, gps_stats = add_relative_gps_and_normalize(
    train_df,
    CONFIG,
    fit_stats=None
)

val_df, _ = add_relative_gps_and_normalize(
    val_df,
    CONFIG,
    fit_stats=gps_stats
)

test_df, _ = add_relative_gps_and_normalize(
    test_df,
    CONFIG,
    fit_stats=gps_stats
)

print("\nRelative GPS sample:")
display(train_df[["rel_lat", "rel_lon"]].head())



train_seq = make_sequence_indices(
    train_df,
    seq_len=CONFIG["seq_len"],
    episode_col=CONFIG["episode_col"]
)

val_seq = make_sequence_indices(
    val_df,
    seq_len=CONFIG["seq_len"],
    episode_col=CONFIG["episode_col"]
)

test_seq = make_sequence_indices(
    test_df,
    seq_len=CONFIG["seq_len"],
    episode_col=CONFIG["episode_col"]
)

print("\nSequence counts:")
print("Train seq:", len(train_seq))
print("Val seq:", len(val_seq))
print("Test seq:", len(test_seq))

assert len(train_seq) > 0, "No train sequences generated!"
assert len(val_seq) > 0, "No val sequences generated!"
assert len(test_seq) > 0, "No test sequences generated!"

train_ds = UAVBeamSequenceDataset(
    train_df,
    root=CONFIG["root"],
    image_col=CONFIG["image_col"],
    label_col=CONFIG["label_col"],
    gps_cols=("rel_lat", "rel_lon"),
    seq_indices=train_seq,
    image_size=CONFIG["image_size"],
    label_is_one_indexed=CONFIG["label_is_one_indexed"],
)

val_ds = UAVBeamSequenceDataset(
    val_df,
    root=CONFIG["root"],
    image_col=CONFIG["image_col"],
    label_col=CONFIG["label_col"],
    gps_cols=("rel_lat", "rel_lon"),
    seq_indices=val_seq,
    image_size=CONFIG["image_size"],
    label_is_one_indexed=CONFIG["label_is_one_indexed"],
)

test_ds = UAVBeamSequenceDataset(
    test_df,
    root=CONFIG["root"],
    image_col=CONFIG["image_col"],
    label_col=CONFIG["label_col"],
    gps_cols=("rel_lat", "rel_lon"),
    seq_indices=test_seq,
    image_size=CONFIG["image_size"],
    label_is_one_indexed=CONFIG["label_is_one_indexed"],
)


BATCH_SIZE = 8

# Debugging stable rakhar jonno num_workers=0.
# Later speed er jonno num_workers=2 dite paren.
train_loader = DataLoader(
    train_ds,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=0,
    pin_memory=False,
    drop_last=True
)

val_loader = DataLoader(
    val_ds,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    pin_memory=False
)

test_loader = DataLoader(
    test_ds,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    pin_memory=False
)



images, gps, labels = next(iter(train_loader))

print("\nFinal batch check:")
print("images:", images.shape)   # [8, 4, 3, 256, 256]
print("gps:", gps.shape)         # [8, 4, 2]
print("labels:", labels.shape)   # [8]
print("label min/max batch:", labels.min().item(), labels.max().item())
print("gps min/max batch:", gps.min().item(), gps.max().item())

assert images.shape == (
    BATCH_SIZE,
    CONFIG["seq_len"],
    3,
    CONFIG["image_size"],
    CONFIG["image_size"]
)

assert gps.shape == (
    BATCH_SIZE,
    CONFIG["seq_len"],
    2
)

assert labels.ndim == 1
assert labels.min().item() >= 0, "Label became negative. Check label_is_one_indexed."
assert labels.max().item() < CONFIG["codebook_size"], "Label exceeds codebook size."

print("\nDataLoader ready with strict seq_index-level split.")

CONFIG root: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev
CSV path: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/scenario23.csv

Data shape: (11387, 17)
Columns: ['index', 'unit1_rgb', 'unit1_pwr_60ghz', 'unit1_loc', 'unit2_loc', 'unit2_speed', 'unit2_altitude', 'unit2_distance', 'unit2_height', 'unit2_x-speed', 'unit2_y-speed', 'unit2_z-speed', 'unit2_pitch', 'unit2_roll', 'seq_index', 'time_stamp[UTC]', 'unit1_beam_index']

Required columns found.

Label min/max BEFORE conversion:
2 60
WARNING: label min is neither 0 nor 1. Check label column manually.
label_is_one_indexed: True

Sample CSV image: ./unit1/camera_data/image_BS1_1_16_58_42.jpg
Resolved image path: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_1_16_58_42.jpg
Image exists: True
Strict seq_index-level split:
Total seq_index: 35
Train seq_index: 24
Val seq_index: 7
Test seq_index: 4

Row counts:
Train rows: 7998
Val rows: 2301
Test rows: 1088

No seq_index overlap between train/val/test.

Split dataframe shapes:
train_df: (7998, 17)
val_df: (2301, 17)
test_df: (1088, 17)

Relative GPS sample:

   rel_lat   rel_lon
0      0.0  0.000000
1      0.0  0.000116
2      0.0  0.000232
3      0.0  0.000348
4      0.0  0.000464

Sequence counts:
Train seq: 7928
Val seq: 2283
Test seq: 1076

Final batch check:
images: torch.Size([8, 4, 3, 256, 256])
gps: torch.Size([8, 4, 2])
labels: torch.Size([8])
label min/max batch: 20 47
gps min/max batch: 0.0 0.9713257551193237

DataLoader ready with strict seq_index-level split.

In [25]:

CONFIG = {
    "root": str(root),
    "csv_path": str(CSV_PATH),

    "image_col": "unit1_rgb",
    "label_col": "unit1_beam_index",
    "episode_col": "seq_index",

    "bs_loc_col": "unit1_loc",
    "uav_loc_col": "unit2_loc",

    "image_size": 256,
    "seq_len": 4,
    "codebook_size": 64,

    # If label min/max is 1..64 -> True
    # If label min/max is 0..63 -> False
    "label_is_one_indexed": True,
}

# Auto fix root
CONFIG["root"] = str(auto_fix_root(CONFIG["root"]))

print("CONFIG root:", CONFIG["root"])
print("CSV path:", CONFIG["csv_path"])



df = pd.read_csv(CONFIG["csv_path"])

print("Data shape:", df.shape)
print("Columns:", list(df.columns))

print("\nLabel min/max BEFORE conversion:")
print(df[CONFIG["label_col"]].min(), df[CONFIG["label_col"]].max())

# Auto detect label indexing
label_min = int(df[CONFIG["label_col"]].min())
label_max = int(df[CONFIG["label_col"]].max())

if label_min == 0:
    CONFIG["label_is_one_indexed"] = False
elif label_min == 1:
    CONFIG["label_is_one_indexed"] = True

print("label_is_one_indexed:", CONFIG["label_is_one_indexed"])



sample_img_value = df.loc[0, CONFIG["image_col"]]
sample_img_path = resolve_path(Path(CONFIG["root"]), sample_img_value)

print("\nSample CSV image:", sample_img_value)
print("Resolved image path:", sample_img_path)
print("Image exists:", sample_img_path.exists())



train_df, val_df, test_df = split_df_sequential(
    df,
    train_ratio=0.7,
    val_ratio=0.2
)

print("\nSplit sizes:")
print("train_df:", train_df.shape)
print("val_df:", val_df.shape)
print("test_df:", test_df.shape)


train_df, gps_stats = add_relative_gps_and_normalize(
    train_df,
    CONFIG,
    fit_stats=None
)

val_df, _ = add_relative_gps_and_normalize(
    val_df,
    CONFIG,
    fit_stats=gps_stats
)

test_df, _ = add_relative_gps_and_normalize(
    test_df,
    CONFIG,
    fit_stats=gps_stats
)

print("\nRelative GPS sample:")
display(train_df[["rel_lat", "rel_lon"]].head())


train_seq = make_sequence_indices(
    train_df,
    seq_len=CONFIG["seq_len"],
    episode_col=CONFIG["episode_col"]
)

val_seq = make_sequence_indices(
    val_df,
    seq_len=CONFIG["seq_len"],
    episode_col=CONFIG["episode_col"]
)

test_seq = make_sequence_indices(
    test_df,
    seq_len=CONFIG["seq_len"],
    episode_col=CONFIG["episode_col"]
)

print("\nSequence counts:")
print("Train seq:", len(train_seq))
print("Val seq:", len(val_seq))
print("Test seq:", len(test_seq))



train_ds = UAVBeamSequenceDataset(
    train_df,
    root=CONFIG["root"],
    image_col=CONFIG["image_col"],
    label_col=CONFIG["label_col"],
    gps_cols=("rel_lat", "rel_lon"),
    seq_indices=train_seq,
    image_size=CONFIG["image_size"],
    label_is_one_indexed=CONFIG["label_is_one_indexed"],
)

val_ds = UAVBeamSequenceDataset(
    val_df,
    root=CONFIG["root"],
    image_col=CONFIG["image_col"],
    label_col=CONFIG["label_col"],
    gps_cols=("rel_lat", "rel_lon"),
    seq_indices=val_seq,
    image_size=CONFIG["image_size"],
    label_is_one_indexed=CONFIG["label_is_one_indexed"],
)

test_ds = UAVBeamSequenceDataset(
    test_df,
    root=CONFIG["root"],
    image_col=CONFIG["image_col"],
    label_col=CONFIG["label_col"],
    gps_cols=("rel_lat", "rel_lon"),
    seq_indices=test_seq,
    image_size=CONFIG["image_size"],
    label_is_one_indexed=CONFIG["label_is_one_indexed"],
)


BATCH_SIZE = 8

# num_workers=0 rakhlam debugging er jonno.
# Later training time speed korte num_workers=2 dite paro.
train_loader = DataLoader(
    train_ds,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=0,
    pin_memory=False,
    drop_last=True
)

val_loader = DataLoader(
    val_ds,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    pin_memory=False
)

test_loader = DataLoader(
    test_ds,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    pin_memory=False
)


images, gps, labels = next(iter(train_loader))

print("\nFinal batch check:")
print("images:", images.shape)   # [8, 4, 3, 256, 256]
print("gps:", gps.shape)         # [8, 4, 2]
print("labels:", labels.shape)   # [8]
print("label min/max batch:", labels.min().item(), labels.max().item())
print("gps min/max batch:", gps.min().item(), gps.max().item())

assert images.shape == (BATCH_SIZE, CONFIG["seq_len"], 3, CONFIG["image_size"], CONFIG["image_size"])
assert gps.shape == (BATCH_SIZE, CONFIG["seq_len"], 2)
assert labels.ndim == 1

print("\n DataLoader ready. Now continue from Model Cell.")

CONFIG root: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev
CSV path: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/scenario23.csv
Data shape: (11387, 17)
Columns: ['index', 'unit1_rgb', 'unit1_pwr_60ghz', 'unit1_loc', 'unit2_loc', 'unit2_speed', 'unit2_altitude', 'unit2_distance', 'unit2_height', 'unit2_x-speed', 'unit2_y-speed', 'unit2_z-speed', 'unit2_pitch', 'unit2_roll', 'seq_index', 'time_stamp[UTC]', 'unit1_beam_index']

Label min/max BEFORE conversion:
2 60
label_is_one_indexed: True

Sample CSV image: ./unit1/camera_data/image_BS1_1_16_58_42.jpg
Resolved image path: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_1_16_58_42.jpg
Image exists: True

Split sizes:
train_df: (7970, 17)
val_df: (2277, 17)
test_df: (1140, 17)

Relative GPS sample:

   rel_lat   rel_lon
0      0.0  0.000000
1      0.0  0.000116
2      0.0  0.000233
3      0.0  0.000349
4      0.0  0.000466

Sequence counts:
Train seq: 7900
Val seq: 2256
Test seq: 1125

Final batch check:
images: torch.Size([8, 4, 3, 256, 256])
gps: torch.Size([8, 4, 2])
labels: torch.Size([8])
label min/max batch: 20 50
gps min/max batch: 0.0 0.9248777031898499

 DataLoader ready. Now continue from Model Cell.

In [15]:
df = pd.read_csv(CONFIG["csv_path"])

train_df, val_df, test_df = split_df_sequential(df, train_ratio=0.7, val_ratio=0.2)

train_df, gps_stats = add_relative_gps_and_normalize(train_df, CONFIG, fit_stats=None)
val_df, _ = add_relative_gps_and_normalize(val_df, CONFIG, fit_stats=gps_stats)
test_df, _ = add_relative_gps_and_normalize(test_df, CONFIG, fit_stats=gps_stats)

train_seq = make_sequence_indices(train_df, CONFIG["seq_len"], CONFIG["episode_col"])
val_seq = make_sequence_indices(val_df, CONFIG["seq_len"], CONFIG["episode_col"])
test_seq = make_sequence_indices(test_df, CONFIG["seq_len"], CONFIG["episode_col"])

print("Train seq:", len(train_seq))
print("Val seq:", len(val_seq))
print("Test seq:", len(test_seq))

train_ds = UAVBeamSequenceDataset(
    train_df,
    root=CONFIG["root"],
    image_col=CONFIG["image_col"],
    label_col=CONFIG["label_col"],
    gps_cols=("rel_lat", "rel_lon"),
    seq_indices=train_seq,
    image_size=CONFIG["image_size"],
    label_is_one_indexed=CONFIG["label_is_one_indexed"],
)

val_ds = UAVBeamSequenceDataset(
    val_df,
    root=CONFIG["root"],
    image_col=CONFIG["image_col"],
    label_col=CONFIG["label_col"],
    gps_cols=("rel_lat", "rel_lon"),
    seq_indices=val_seq,
    image_size=CONFIG["image_size"],
    label_is_one_indexed=CONFIG["label_is_one_indexed"],
)

test_ds = UAVBeamSequenceDataset(
    test_df,
    root=CONFIG["root"],
    image_col=CONFIG["image_col"],
    label_col=CONFIG["label_col"],
    gps_cols=("rel_lat", "rel_lon"),
    seq_indices=test_seq,
    image_size=CONFIG["image_size"],
    label_is_one_indexed=CONFIG["label_is_one_indexed"],
)

BATCH_SIZE = 8

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True, drop_last=True)
val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)
test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

images, gps, labels = next(iter(train_loader))
print("images:", images.shape)   # B,4,3,256,256
print("gps:", gps.shape)         # B,4,2
print("labels:", labels.shape)
print("label min/max:", labels.min().item(), labels.max().item())

Train seq: 7900
Val seq: 2256
Test seq: 1125

FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/worker.py", line 358, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/tmp/ipykernel_843/2516067578.py", line 135, in __getitem__
    [self._load_image(row) for _, row in rows.iterrows()],
     ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_843/2516067578.py", line 124, in _load_image
    raise FileNotFoundError(f"Image not found: {img_path}")
FileNotFoundError: Image not found: /content/uav_beam_tracking_replica/data/scenario23/unit1/camera_data/image_BS1_1379_17_02_12.jpg

In [11]:
print("CSV_PATH:", CSV_PATH)
print("Shape:", df.shape)
print("Columns:")
for i, c in enumerate(df.columns):
    print(i, repr(c))

display(df.head())

CSV_PATH: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/scenario23.csv
Shape: (11387, 17)
Columns:
0 'index'
1 'unit1_rgb'
2 'unit1_pwr_60ghz'
3 'unit1_loc'
4 'unit2_loc'
5 'unit2_speed'
6 'unit2_altitude'
7 'unit2_distance'
8 'unit2_height'
9 'unit2_x-speed'
10 'unit2_y-speed'
11 'unit2_z-speed'
12 'unit2_pitch'
13 'unit2_roll'
14 'seq_index'
15 'time_stamp[UTC]'
16 'unit1_beam_index'

,index,unit1_rgb,unit1_pwr_60ghz,unit1_loc,unit2_loc,unit2_speed,unit2_altitude,unit2_distance,unit2_height,unit2_x-speed,unit2_y-speed,unit2_z-speed,unit2_pitch,unit2_roll,seq_index,time_stamp[UTC],unit1_beam_index
0,1,./unit1/camera_data/image_BS1_1_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_1.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_1.txt,./unit2/speed/speed_1.txt,./unit2/altitude/altitude_1.txt,./unit2/distance/distance_1.txt,./unit2/height/height_1.txt,./unit2/x_speed/x_speed_1.txt,./unit2/y_speed/y_speed_1.txt,./unit2/z_speed/z_speed_1.txt,./unit2/pitch/pitch_1.txt,./unit2/roll/roll_1.txt,1,['16-58-42-0'],43
1,2,./unit1/camera_data/image_BS1_2_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_2.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_2.txt,./unit2/speed/speed_2.txt,./unit2/altitude/altitude_2.txt,./unit2/distance/distance_2.txt,./unit2/height/height_2.txt,./unit2/x_speed/x_speed_2.txt,./unit2/y_speed/y_speed_2.txt,./unit2/z_speed/z_speed_2.txt,./unit2/pitch/pitch_2.txt,./unit2/roll/roll_2.txt,1,['16-58-42-142'],43
2,3,./unit1/camera_data/image_BS1_3_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_3.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_3.txt,./unit2/speed/speed_3.txt,./unit2/altitude/altitude_3.txt,./unit2/distance/distance_3.txt,./unit2/height/height_3.txt,./unit2/x_speed/x_speed_3.txt,./unit2/y_speed/y_speed_3.txt,./unit2/z_speed/z_speed_3.txt,./unit2/pitch/pitch_3.txt,./unit2/roll/roll_3.txt,1,['16-58-42-284'],43
3,4,./unit1/camera_data/image_BS1_4_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_4.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_4.txt,./unit2/speed/speed_4.txt,./unit2/altitude/altitude_4.txt,./unit2/distance/distance_4.txt,./unit2/height/height_4.txt,./unit2/x_speed/x_speed_4.txt,./unit2/y_speed/y_speed_4.txt,./unit2/z_speed/z_speed_4.txt,./unit2/pitch/pitch_4.txt,./unit2/roll/roll_4.txt,1,['16-58-42-426'],43
4,5,./unit1/camera_data/image_BS1_5_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_5.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_5.txt,./unit2/speed/speed_5.txt,./unit2/altitude/altitude_5.txt,./unit2/distance/distance_5.txt,./unit2/height/height_5.txt,./unit2/x_speed/x_speed_5.txt,./unit2/y_speed/y_speed_5.txt,./unit2/z_speed/z_speed_5.txt,./unit2/pitch/pitch_5.txt,./unit2/roll/roll_5.txt,1,['16-58-42-568'],39

In [16]:
from pathlib import Path

root = Path(CONFIG["root"])

target_name = "image_BS1_1379_17_02_12.jpg"

matches = list(root.rglob(target_name))

print("ROOT:", root)
print("Matches found:", len(matches))

for m in matches[:10]:
    print(m)

ROOT: /content/uav_beam_tracking_replica/data/scenario23
Matches found: 1
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_1379_17_02_12.jpg

In [20]:
from pathlib import Path

root = Path(CONFIG["root"])

jpgs = list(root.rglob("*.jpg"))
pngs = list(root.rglob("*.png"))
jpeg = list(root.rglob("*.jpeg"))

print("jpg:", len(jpgs))
print("png:", len(pngs))
print("jpeg:", len(jpeg))

for p in jpgs[:20]:
    print(p)

jpg: 11387
png: 0
jpeg: 0
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_2568_17_05_32.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_7570_17_48_29.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_5481_17_15_01.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_4715_17_12_54.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_1260_17_01_50.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_7204_17_47_39.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_2864_17_06_19.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_7483_17_48_17.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_6286_17_44_57.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_11314_18_00_13.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_10383_17_56_59.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_7388_17_48_04.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_1082_17_01_24.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_11976_18_02_17.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_11585_18_00_56.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_1855_17_03_39.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_11537_18_00_48.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_3359_17_07_33.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_3876_17_09_17.jpg
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_2590_17_05_35.jpg

In [21]:
from pathlib import Path

old_root = Path(CONFIG["root"])

jpgs = list(old_root.rglob("*.jpg"))
print("Total jpg:", len(jpgs))
print("First jpg:", jpgs[0])

def find_dataset_root_from_image(img_path):
    """
    CSV image path starts like:
        ./unit1/camera_data/image_xxx.jpg
    
    So correct root is the folder that contains:
        unit1/camera_data/
    """
    img_path = Path(img_path)

    for parent in img_path.parents:
        if (parent / "unit1").exists():
            if (parent / "unit1" / "camera_data").exists():
                return parent

    return None

correct_root = find_dataset_root_from_image(jpgs[0])

print("Old CONFIG root:", CONFIG["root"])
print("Detected correct root:", correct_root)

CONFIG["root"] = str(correct_root)

print("Updated CONFIG root:", CONFIG["root"])

Total jpg: 11387
First jpg: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_2568_17_05_32.jpg
Old CONFIG root: /content/uav_beam_tracking_replica/data/scenario23
Detected correct root: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev
Updated CONFIG root: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev

In [22]:


sample_img_value = df.loc[0, CONFIG["image_col"]]
sample_img_path = Path(CONFIG["root"]) / str(sample_img_value).replace("./", "")

print("CONFIG root:", CONFIG["root"])
print("CSV image:", sample_img_value)
print("Resolved:", sample_img_path)
print("Exists:", sample_img_path.exists())

CONFIG root: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev
CSV image: ./unit1/camera_data/image_BS1_1_16_58_42.jpg
Resolved: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_1_16_58_42.jpg
Exists: True