In [1]:
from google.colab import drive
drive.mount('/content/drive')

import os, zipfile, shutil
from pathlib import Path

WORK_DIR = Path("/content/uav_beam_tracking_replica")
DATA_DIR = WORK_DIR / "data"
CODE_DIR = WORK_DIR / "code"
OUT_DIR = WORK_DIR / "outputs"

for p in [WORK_DIR, DATA_DIR, CODE_DIR, OUT_DIR]:
    p.mkdir(parents=True, exist_ok=True)

print("WORK_DIR:", WORK_DIR)
print("DATA_DIR:", DATA_DIR)
print("CODE_DIR:", CODE_DIR)

Mounted at /content/drive
WORK_DIR: /content/uav_beam_tracking_replica
DATA_DIR: /content/uav_beam_tracking_replica/data
CODE_DIR: /content/uav_beam_tracking_replica/code

In [2]:
from pathlib import Path

# CHANGE THIS PATH based on your Drive location
DATASET_ZIP = Path("/content/drive/MyDrive/scenario23_dev_w_resources.zip")

print("Exists:", DATASET_ZIP.exists())
print("Path:", DATASET_ZIP)

Exists: True
Path: /content/drive/MyDrive/scenario23_dev_w_resources.zip

In [3]:
import zipfile, os
from pathlib import Path

EXTRACT_DIR = DATA_DIR / "scenario23"
EXTRACT_DIR.mkdir(parents=True, exist_ok=True)

if not any(EXTRACT_DIR.iterdir()):
    with zipfile.ZipFile(DATASET_ZIP, "r") as z:
        z.extractall(EXTRACT_DIR)
    print("Unzipped to:", EXTRACT_DIR)
else:
    print("Already extracted:", EXTRACT_DIR)

!find /content/uav_beam_tracking_replica/data/scenario23 -maxdepth 3 -type f | head -30

Unzipped to: /content/uav_beam_tracking_replica/data/scenario23
/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/scenario23.csv

In [4]:
!pip install -q torch torchvision torchaudio
!pip install -q pandas numpy pillow pyyaml tqdm scikit-learn ultralytics

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 43.0 MB/s eta 0:00:00

In [5]:
import os
from pathlib import Path
import pandas as pd

root = Path("/content/uav_beam_tracking_replica/data/scenario23")

print("CSV files:")
csv_files = list(root.rglob("*.csv"))
for i, p in enumerate(csv_files):
    print(i, p)

print("\nImage samples:")
for ext in ["*.jpg", "*.jpeg", "*.png"]:
    imgs = list(root.rglob(ext))
    if imgs:
        print(ext, len(imgs), imgs[0])
        break

CSV files:
0 /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/scenario23.csv

Image samples:
*.jpg 11387 /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/unit1/camera_data/image_BS1_2568_17_05_32.jpg

In [6]:
import pandas as pd

CSV_PATH = csv_files[0]
df = pd.read_csv(CSV_PATH)

print("CSV_PATH:", CSV_PATH)
print("Shape:", df.shape)
print("Columns:")
print(list(df.columns))

display(df.head())

CSV_PATH: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/scenario23.csv
Shape: (11387, 17)
Columns:
['index', 'unit1_rgb', 'unit1_pwr_60ghz', 'unit1_loc', 'unit2_loc', 'unit2_speed', 'unit2_altitude', 'unit2_distance', 'unit2_height', 'unit2_x-speed', 'unit2_y-speed', 'unit2_z-speed', 'unit2_pitch', 'unit2_roll', 'seq_index', 'time_stamp[UTC]', 'unit1_beam_index']

,index,unit1_rgb,unit1_pwr_60ghz,unit1_loc,unit2_loc,unit2_speed,unit2_altitude,unit2_distance,unit2_height,unit2_x-speed,unit2_y-speed,unit2_z-speed,unit2_pitch,unit2_roll,seq_index,time_stamp[UTC],unit1_beam_index
0,1,./unit1/camera_data/image_BS1_1_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_1.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_1.txt,./unit2/speed/speed_1.txt,./unit2/altitude/altitude_1.txt,./unit2/distance/distance_1.txt,./unit2/height/height_1.txt,./unit2/x_speed/x_speed_1.txt,./unit2/y_speed/y_speed_1.txt,./unit2/z_speed/z_speed_1.txt,./unit2/pitch/pitch_1.txt,./unit2/roll/roll_1.txt,1,['16-58-42-0'],43
1,2,./unit1/camera_data/image_BS1_2_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_2.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_2.txt,./unit2/speed/speed_2.txt,./unit2/altitude/altitude_2.txt,./unit2/distance/distance_2.txt,./unit2/height/height_2.txt,./unit2/x_speed/x_speed_2.txt,./unit2/y_speed/y_speed_2.txt,./unit2/z_speed/z_speed_2.txt,./unit2/pitch/pitch_2.txt,./unit2/roll/roll_2.txt,1,['16-58-42-142'],43
2,3,./unit1/camera_data/image_BS1_3_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_3.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_3.txt,./unit2/speed/speed_3.txt,./unit2/altitude/altitude_3.txt,./unit2/distance/distance_3.txt,./unit2/height/height_3.txt,./unit2/x_speed/x_speed_3.txt,./unit2/y_speed/y_speed_3.txt,./unit2/z_speed/z_speed_3.txt,./unit2/pitch/pitch_3.txt,./unit2/roll/roll_3.txt,1,['16-58-42-284'],43
3,4,./unit1/camera_data/image_BS1_4_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_4.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_4.txt,./unit2/speed/speed_4.txt,./unit2/altitude/altitude_4.txt,./unit2/distance/distance_4.txt,./unit2/height/height_4.txt,./unit2/x_speed/x_speed_4.txt,./unit2/y_speed/y_speed_4.txt,./unit2/z_speed/z_speed_4.txt,./unit2/pitch/pitch_4.txt,./unit2/roll/roll_4.txt,1,['16-58-42-426'],43
4,5,./unit1/camera_data/image_BS1_5_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_5.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_5.txt,./unit2/speed/speed_5.txt,./unit2/altitude/altitude_5.txt,./unit2/distance/distance_5.txt,./unit2/height/height_5.txt,./unit2/x_speed/x_speed_5.txt,./unit2/y_speed/y_speed_5.txt,./unit2/z_speed/z_speed_5.txt,./unit2/pitch/pitch_5.txt,./unit2/roll/roll_5.txt,1,['16-58-42-568'],39

In [7]:
cols = list(df.columns)

def find_cols(keywords):
    out = []
    for c in cols:
        low = c.lower()
        if any(k in low for k in keywords):
            out.append(c)
    return out

print("Possible image columns:", find_cols(["image", "img", "rgb", "camera"]))
print("Possible beam columns:", find_cols(["beam", "label", "index", "power"]))
print("Possible lat columns:", find_cols(["lat"]))
print("Possible lon columns:", find_cols(["lon", "lng", "long"]))
print("Possible episode columns:", find_cols(["episode", "scene", "unit", "run", "traj"]))

Possible image columns: ['unit1_rgb']
Possible beam columns: ['index', 'seq_index', 'unit1_beam_index']
Possible lat columns: []
Possible lon columns: []
Possible episode columns: ['unit1_rgb', 'unit1_pwr_60ghz', 'unit1_loc', 'unit2_loc', 'unit2_speed', 'unit2_altitude', 'unit2_distance', 'unit2_height', 'unit2_x-speed', 'unit2_y-speed', 'unit2_z-speed', 'unit2_pitch', 'unit2_roll', 'unit1_beam_index']

In [12]:
CONFIG = {
    "root": str(root),
    "csv_path": str(CSV_PATH),

    "image_col": "unit1_rgb",
    "label_col": "unit1_beam_index",
    "episode_col": "seq_index",

    "bs_loc_col": "unit1_loc",
    "uav_loc_col": "unit2_loc",

    "image_size": 256,
    "seq_len": 4,
    "codebook_size": 64,

    # DeepSense beam index usually 1..64 হলে True লাগবে
    "label_is_one_indexed": True,
}

print(CONFIG)

{'root': '/content/uav_beam_tracking_replica/data/scenario23', 'csv_path': '/content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/scenario23.csv', 'image_col': 'unit1_rgb', 'label_col': 'unit1_beam_index', 'episode_col': 'seq_index', 'bs_loc_col': 'unit1_loc', 'uav_loc_col': 'unit2_loc', 'image_size': 256, 'seq_len': 4, 'codebook_size': 64, 'label_is_one_indexed': True}

In [9]:
from pathlib import Path
from typing import List, Tuple, Dict
import pandas as pd
from PIL import Image

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms


def resolve_path(root: Path, value: str) -> Path:
    p = Path(str(value))
    if p.is_absolute():
        return p
    return root / p


class UAVBeamSequenceDataset(Dataset):
    def __init__(
        self,
        df: pd.DataFrame,
        root: str,
        image_col: str,
        label_col: str,
        gps_cols: Tuple[str, str],
        seq_indices: List[List[int]],
        image_size: int = 256,
        label_is_one_indexed: bool = False,
    ):
        self.df = df.reset_index(drop=True)
        self.root = Path(root)
        self.image_col = image_col
        self.label_col = label_col
        self.gps_cols = gps_cols
        self.seq_indices = seq_indices
        self.label_is_one_indexed = label_is_one_indexed

        self.transform = transforms.Compose([
            transforms.Resize((image_size, image_size)),
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225],
            ),
        ])

    def __len__(self):
        return len(self.seq_indices)

    def _load_image(self, row):
        path = resolve_path(self.root, row[self.image_col])
        img = Image.open(path).convert("RGB")
        return self.transform(img)

    def __getitem__(self, idx):
        ids = self.seq_indices[idx]
        rows = self.df.iloc[ids]

        images = torch.stack(
            [self._load_image(row) for _, row in rows.iterrows()],
            dim=0
        )  # T,3,H,W

        gps = torch.tensor(
            rows.loc[:, list(self.gps_cols)].values,
            dtype=torch.float32
        )  # T,2

        label = int(rows.iloc[-1][self.label_col])
        if self.label_is_one_indexed:
            label -= 1

        return images, gps, torch.tensor(label, dtype=torch.long)


def add_relative_gps_and_normalize(df, cfg, fit_stats=None):
    df = df.copy()

    df["rel_lat"] = df[cfg["uav_lat_col"]].astype(float) - df[cfg["bs_lat_col"]].astype(float)
    df["rel_lon"] = df[cfg["uav_lon_col"]].astype(float) - df[cfg["bs_lon_col"]].astype(float)

    cols = ["rel_lat", "rel_lon"]

    if fit_stats is None:
        fit_stats = {
            "min": df[cols].min(),
            "max": df[cols].max(),
        }

    denom = (fit_stats["max"] - fit_stats["min"]).replace(0, 1.0)
    df[cols] = (df[cols] - fit_stats["min"]) / denom

    return df, fit_stats


def make_sequence_indices(df, seq_len=4, episode_col=None):
    seqs = []

    if episode_col is not None and episode_col in df.columns:
        groups = [list(g) for g in df.groupby(episode_col, sort=False).indices.values()]
    else:
        groups = [list(range(len(df)))]

    for g in groups:
        for start in range(0, len(g) - seq_len + 1):
            seqs.append(g[start:start + seq_len])

    return seqs


def split_df_sequential(df, train_ratio=0.7, val_ratio=0.2):
    n = len(df)
    n_train = int(n * train_ratio)
    n_val = int(n * val_ratio)

    train_df = df.iloc[:n_train].reset_index(drop=True)
    val_df = df.iloc[n_train:n_train+n_val].reset_index(drop=True)
    test_df = df.iloc[n_train+n_val:].reset_index(drop=True)

    return train_df, val_df, test_df

dataloader build

In [10]:
df = pd.read_csv(CONFIG["csv_path"])

train_df, val_df, test_df = split_df_sequential(df, train_ratio=0.7, val_ratio=0.2)

train_df, gps_stats = add_relative_gps_and_normalize(train_df, CONFIG, fit_stats=None)
val_df, _ = add_relative_gps_and_normalize(val_df, CONFIG, fit_stats=gps_stats)
test_df, _ = add_relative_gps_and_normalize(test_df, CONFIG, fit_stats=gps_stats)

train_seq = make_sequence_indices(train_df, CONFIG["seq_len"], CONFIG["episode_col"])
val_seq = make_sequence_indices(val_df, CONFIG["seq_len"], CONFIG["episode_col"])
test_seq = make_sequence_indices(test_df, CONFIG["seq_len"], CONFIG["episode_col"])

print("Train seq:", len(train_seq))
print("Val seq:", len(val_seq))
print("Test seq:", len(test_seq))

train_ds = UAVBeamSequenceDataset(
    train_df,
    root=CONFIG["root"],
    image_col=CONFIG["image_col"],
    label_col=CONFIG["label_col"],
    gps_cols=("rel_lat", "rel_lon"),
    seq_indices=train_seq,
    image_size=CONFIG["image_size"],
    label_is_one_indexed=CONFIG["label_is_one_indexed"],
)

val_ds = UAVBeamSequenceDataset(
    val_df,
    root=CONFIG["root"],
    image_col=CONFIG["image_col"],
    label_col=CONFIG["label_col"],
    gps_cols=("rel_lat", "rel_lon"),
    seq_indices=val_seq,
    image_size=CONFIG["image_size"],
    label_is_one_indexed=CONFIG["label_is_one_indexed"],
)

test_ds = UAVBeamSequenceDataset(
    test_df,
    root=CONFIG["root"],
    image_col=CONFIG["image_col"],
    label_col=CONFIG["label_col"],
    gps_cols=("rel_lat", "rel_lon"),
    seq_indices=test_seq,
    image_size=CONFIG["image_size"],
    label_is_one_indexed=CONFIG["label_is_one_indexed"],
)

BATCH_SIZE = 8

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True, drop_last=True)
val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)
test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

images, gps, labels = next(iter(train_loader))
print("images:", images.shape)   # B,4,3,256,256
print("gps:", gps.shape)         # B,4,2
print("labels:", labels.shape)
print("label min/max:", labels.min().item(), labels.max().item())

KeyError: 'uav_lat'

In [11]:
print("CSV_PATH:", CSV_PATH)
print("Shape:", df.shape)
print("Columns:")
for i, c in enumerate(df.columns):
    print(i, repr(c))

display(df.head())

CSV_PATH: /content/uav_beam_tracking_replica/data/scenario23/scenario23_dev/scenario23.csv
Shape: (11387, 17)
Columns:
0 'index'
1 'unit1_rgb'
2 'unit1_pwr_60ghz'
3 'unit1_loc'
4 'unit2_loc'
5 'unit2_speed'
6 'unit2_altitude'
7 'unit2_distance'
8 'unit2_height'
9 'unit2_x-speed'
10 'unit2_y-speed'
11 'unit2_z-speed'
12 'unit2_pitch'
13 'unit2_roll'
14 'seq_index'
15 'time_stamp[UTC]'
16 'unit1_beam_index'

,index,unit1_rgb,unit1_pwr_60ghz,unit1_loc,unit2_loc,unit2_speed,unit2_altitude,unit2_distance,unit2_height,unit2_x-speed,unit2_y-speed,unit2_z-speed,unit2_pitch,unit2_roll,seq_index,time_stamp[UTC],unit1_beam_index
0,1,./unit1/camera_data/image_BS1_1_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_1.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_1.txt,./unit2/speed/speed_1.txt,./unit2/altitude/altitude_1.txt,./unit2/distance/distance_1.txt,./unit2/height/height_1.txt,./unit2/x_speed/x_speed_1.txt,./unit2/y_speed/y_speed_1.txt,./unit2/z_speed/z_speed_1.txt,./unit2/pitch/pitch_1.txt,./unit2/roll/roll_1.txt,1,['16-58-42-0'],43
1,2,./unit1/camera_data/image_BS1_2_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_2.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_2.txt,./unit2/speed/speed_2.txt,./unit2/altitude/altitude_2.txt,./unit2/distance/distance_2.txt,./unit2/height/height_2.txt,./unit2/x_speed/x_speed_2.txt,./unit2/y_speed/y_speed_2.txt,./unit2/z_speed/z_speed_2.txt,./unit2/pitch/pitch_2.txt,./unit2/roll/roll_2.txt,1,['16-58-42-142'],43
2,3,./unit1/camera_data/image_BS1_3_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_3.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_3.txt,./unit2/speed/speed_3.txt,./unit2/altitude/altitude_3.txt,./unit2/distance/distance_3.txt,./unit2/height/height_3.txt,./unit2/x_speed/x_speed_3.txt,./unit2/y_speed/y_speed_3.txt,./unit2/z_speed/z_speed_3.txt,./unit2/pitch/pitch_3.txt,./unit2/roll/roll_3.txt,1,['16-58-42-284'],43
3,4,./unit1/camera_data/image_BS1_4_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_4.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_4.txt,./unit2/speed/speed_4.txt,./unit2/altitude/altitude_4.txt,./unit2/distance/distance_4.txt,./unit2/height/height_4.txt,./unit2/x_speed/x_speed_4.txt,./unit2/y_speed/y_speed_4.txt,./unit2/z_speed/z_speed_4.txt,./unit2/pitch/pitch_4.txt,./unit2/roll/roll_4.txt,1,['16-58-42-426'],43
4,5,./unit1/camera_data/image_BS1_5_16_58_42.jpg,./unit1/mmWave_data/mmWave_power_5.txt,./unit1/GPS_data/gps_location.txt,./unit2/GPS_data/gps_location_5.txt,./unit2/speed/speed_5.txt,./unit2/altitude/altitude_5.txt,./unit2/distance/distance_5.txt,./unit2/height/height_5.txt,./unit2/x_speed/x_speed_5.txt,./unit2/y_speed/y_speed_5.txt,./unit2/z_speed/z_speed_5.txt,./unit2/pitch/pitch_5.txt,./unit2/roll/roll_5.txt,1,['16-58-42-568'],39