In [95]:
import os
import copy
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [96]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [97]:
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

Device: cuda

In [98]:
drive_root = "/content/drive/MyDrive"

pos_matches = []
for root, dirs, files in os.walk(drive_root):
    needed = {
        "scenario23_pos_beam_train.csv",
        "scenario23_pos_beam_val.csv",
        "scenario23_pos_beam_test.csv"
    }
    if needed.issubset(set(files)):
        pos_matches.append(root)

print("Position CSV folder candidates:")
for p in pos_matches:
    print(p)

Position CSV folder candidates:
/content/drive/MyDrive/Pos beam

In [99]:
POS_ROOT = "/content/drive/MyDrive/Pos beam"

pos_train_csv = os.path.join(POS_ROOT, "scenario23_pos_beam_train.csv")
pos_val_csv   = os.path.join(POS_ROOT, "scenario23_pos_beam_val.csv")
pos_test_csv  = os.path.join(POS_ROOT, "scenario23_pos_beam_test.csv")

print(os.path.exists(pos_train_csv), pos_train_csv)
print(os.path.exists(pos_val_csv), pos_val_csv)
print(os.path.exists(pos_test_csv), pos_test_csv)

True /content/drive/MyDrive/Pos beam/scenario23_pos_beam_train.csv
True /content/drive/MyDrive/Pos beam/scenario23_pos_beam_val.csv
True /content/drive/MyDrive/Pos beam/scenario23_pos_beam_test.csv

In [100]:
train_pos_df = pd.read_csv(pos_train_csv)
val_pos_df   = pd.read_csv(pos_val_csv)
test_pos_df  = pd.read_csv(pos_test_csv)

print("Train:", train_pos_df.shape)
print("Val  :", val_pos_df.shape)
print("Test :", test_pos_df.shape)

print(train_pos_df.head())
print(train_pos_df.columns.tolist())

Train: (6832, 3)
Val  : (3416, 3)
Test : (1139, 3)
   index                                  unit2_pos  unit1_beam
0   3532    [0.8092883966431671, 0.521083920903955]          17
1   2224  [0.4816276084988933, 0.29434536152734486]          14
2   9416    [0.220278556834608, 0.4136596156292844]          17
3   8510  [0.21412273613497904, 0.4547214157104936]          20
4   6877  [0.14500641727379412, 0.4097884695072434]          17
['index', 'unit2_pos', 'unit1_beam']

In [101]:
label_col = train_pos_df.columns[-1]
feature_cols = [c for c in train_pos_df.columns if c != label_col]

print("Feature columns:", feature_cols)
print("Label column:", label_col)

print("Label min/max:", train_pos_df[label_col].min(), train_pos_df[label_col].max())

Feature columns: ['index', 'unit2_pos']
Label column: unit1_beam
Label min/max: 2 30

In [102]:
import ast

def parse_unit2_pos(pos_value):
    if isinstance(pos_value, str):
        return ast.literal_eval(pos_value)
    return pos_value

for df in [train_pos_df, val_pos_df, test_pos_df]:
    parsed = df["unit2_pos"].apply(parse_unit2_pos)
    df["pos_x"] = parsed.apply(lambda v: float(v[0]))
    df["pos_y"] = parsed.apply(lambda v: float(v[1]))

feature_cols = ["pos_x", "pos_y"]
label_col = "unit1_beam"

print(train_pos_df[["index", "unit2_pos", "pos_x", "pos_y", label_col]].head())
print("Feature columns:", feature_cols)
print("Label column:", label_col)
print("Original label min/max:", train_pos_df[label_col].min(), train_pos_df[label_col].max())
print("Unique labels:", sorted(train_pos_df[label_col].unique()))

   index                                  unit2_pos     pos_x     pos_y  \
0   3532    [0.8092883966431671, 0.521083920903955]  0.809288  0.521084
1   2224  [0.4816276084988933, 0.29434536152734486]  0.481628  0.294345
2   9416    [0.220278556834608, 0.4136596156292844]  0.220279  0.413660
3   8510  [0.21412273613497904, 0.4547214157104936]  0.214123  0.454721
4   6877  [0.14500641727379412, 0.4097884695072434]  0.145006  0.409788

   unit1_beam
0          17
1          14
2          17
3          20
4          17
Feature columns: ['pos_x', 'pos_y']
Label column: unit1_beam
Original label min/max: 2 30
Unique labels: [np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30)]

label remapping

In [103]:
import ast
import numpy as np

def parse_unit2_pos(pos_value):
    if isinstance(pos_value, str):
        return ast.literal_eval(pos_value)
    return pos_value

for df in [train_pos_df, val_pos_df, test_pos_df]:
    parsed = df["unit2_pos"].apply(parse_unit2_pos)
    df["pos_x"] = parsed.apply(lambda v: float(v[0]))
    df["pos_y"] = parsed.apply(lambda v: float(v[1]))

    df["distance"] = np.sqrt(df["pos_x"]**2 + df["pos_y"]**2)
    df["angle"] = np.arctan2(df["pos_y"], df["pos_x"])
    df["sin_angle"] = np.sin(df["angle"])
    df["cos_angle"] = np.cos(df["angle"])

    df["pos_x2"] = df["pos_x"] ** 2
    df["pos_y2"] = df["pos_y"] ** 2
    df["pos_xy"] = df["pos_x"] * df["pos_y"]

feature_cols = [
    "pos_x",
    "pos_y",
    "distance",
    "sin_angle",
    "cos_angle",
    "pos_x2",
    "pos_y2",
    "pos_xy",
]

label_col = "unit1_beam"

print(train_pos_df[["index", "unit2_pos", *feature_cols, label_col]].head())
print("Feature columns:", feature_cols)
print("Number of features:", len(feature_cols))
print("Label column:", label_col)
print("Original label min/max:", train_pos_df[label_col].min(), train_pos_df[label_col].max())

   index                                  unit2_pos     pos_x     pos_y  \
0   3532    [0.8092883966431671, 0.521083920903955]  0.809288  0.521084
1   2224  [0.4816276084988933, 0.29434536152734486]  0.481628  0.294345
2   9416    [0.220278556834608, 0.4136596156292844]  0.220279  0.413660
3   8510  [0.21412273613497904, 0.4547214157104936]  0.214123  0.454721
4   6877  [0.14500641727379412, 0.4097884695072434]  0.145006  0.409788

   distance  sin_angle  cos_angle    pos_x2    pos_y2    pos_xy  unit1_beam
0  0.962536   0.541365   0.840787  0.654948  0.271528  0.421707          17
1  0.564450   0.521472   0.853268  0.231965  0.086639  0.141765          14
2  0.468654   0.882654   0.470023  0.048523  0.171114  0.091120          17
3  0.502613   0.904714   0.426019  0.045849  0.206772  0.097366          20
4  0.434688   0.942719   0.333588  0.021027  0.167927  0.059422          17
Feature columns: ['pos_x', 'pos_y', 'distance', 'sin_angle', 'cos_angle', 'pos_x2', 'pos_y2', 'pos_xy']
Number of features: 8
Label column: unit1_beam
Original label min/max: 2 30

new feature

In [104]:
import ast
import numpy as np

def parse_unit2_pos(pos_value):
    if isinstance(pos_value, str):
        return ast.literal_eval(pos_value)
    return pos_value

eps = 1e-8

for df in [train_pos_df, val_pos_df, test_pos_df]:
    parsed = df["unit2_pos"].apply(parse_unit2_pos)

    df["pos_x"] = parsed.apply(lambda v: float(v[0]))
    df["pos_y"] = parsed.apply(lambda v: float(v[1]))

    df["distance"] = np.sqrt(df["pos_x"]**2 + df["pos_y"]**2)
    df["distance2"] = df["distance"] ** 2
    df["distance3"] = df["distance"] ** 3

    df["angle"] = np.arctan2(df["pos_y"], df["pos_x"])
    df["sin_angle"] = np.sin(df["angle"])
    df["cos_angle"] = np.cos(df["angle"])

    df["pos_x2"] = df["pos_x"] ** 2
    df["pos_y2"] = df["pos_y"] ** 2
    df["pos_x3"] = df["pos_x"] ** 3
    df["pos_y3"] = df["pos_y"] ** 3
    df["pos_xy"] = df["pos_x"] * df["pos_y"]

    df["unit_x"] = df["pos_x"] / (df["distance"] + eps)
    df["unit_y"] = df["pos_y"] / (df["distance"] + eps)

feature_cols = [
    "pos_x",
    "pos_y",
    "distance",
    "distance2",
    "distance3",
    "sin_angle",
    "cos_angle",
    "pos_x2",
    "pos_y2",
    "pos_x3",
    "pos_y3",
    "pos_xy",
    "unit_x",
    "unit_y",
]

label_col = "unit1_beam"

print("Feature columns:", feature_cols)
print("Number of features:", len(feature_cols))
print("Label column:", label_col)

display(train_pos_df[["index", "unit2_pos", *feature_cols, label_col]].head())
print("Label unique:", train_pos_df[label_col].nunique())
print("Label min/max:", train_pos_df[label_col].min(), train_pos_df[label_col].max())

Feature columns: ['pos_x', 'pos_y', 'distance', 'distance2', 'distance3', 'sin_angle', 'cos_angle', 'pos_x2', 'pos_y2', 'pos_x3', 'pos_y3', 'pos_xy', 'unit_x', 'unit_y']
Number of features: 14
Label column: unit1_beam

,index,unit2_pos,pos_x,pos_y,distance,distance2,distance3,sin_angle,cos_angle,pos_x2,pos_y2,pos_x3,pos_y3,pos_xy,unit_x,unit_y,unit1_beam
0,3532,"[0.8092883966431671, 0.521083920903955]",0.809288,0.521084,0.962536,0.926476,0.891767,0.541365,0.840787,0.654948,0.271528,0.530042,0.141489,0.421707,0.840787,0.541365,17
1,2224,"[0.4816276084988933, 0.29434536152734486]",0.481628,0.294345,0.564450,0.318604,0.179836,0.521472,0.853268,0.231965,0.086639,0.111721,0.025502,0.141765,0.853268,0.521472,14
2,9416,"[0.220278556834608, 0.4136596156292844]",0.220279,0.413660,0.468654,0.219637,0.102934,0.882654,0.470023,0.048523,0.171114,0.010688,0.070783,0.091120,0.470023,0.882654,17
3,8510,"[0.21412273613497904, 0.4547214157104936]",0.214123,0.454721,0.502613,0.252620,0.126970,0.904714,0.426019,0.045849,0.206772,0.009817,0.094023,0.097366,0.426019,0.904714,20
4,6877,"[0.14500641727379412, 0.4097884695072434]",0.145006,0.409788,0.434688,0.188953,0.082136,0.942719,0.333588,0.021027,0.167927,0.003049,0.068814,0.059422,0.333588,0.942719,17

Label unique: 29
Label min/max: 2 30

In [105]:
all_labels = sorted(train_pos_df[label_col].unique())

label_to_id = {label: i for i, label in enumerate(all_labels)}
id_to_label = {i: label for label, i in label_to_id.items()}

num_classes_pos = len(all_labels)

print("Number of position classes:", num_classes_pos)
print("Label mapping:", label_to_id)

Number of position classes: 29
Label mapping: {np.int64(2): 0, np.int64(3): 1, np.int64(4): 2, np.int64(5): 3, np.int64(6): 4, np.int64(7): 5, np.int64(8): 6, np.int64(9): 7, np.int64(10): 8, np.int64(11): 9, np.int64(12): 10, np.int64(13): 11, np.int64(14): 12, np.int64(15): 13, np.int64(16): 14, np.int64(17): 15, np.int64(18): 16, np.int64(19): 17, np.int64(20): 18, np.int64(21): 19, np.int64(22): 20, np.int64(23): 21, np.int64(24): 22, np.int64(25): 23, np.int64(26): 24, np.int64(27): 25, np.int64(28): 26, np.int64(29): 27, np.int64(30): 28}

morm- only pos x,y

In [74]:
train_mean = train_pos_df[feature_cols].astype(float).mean()
train_std  = train_pos_df[feature_cols].astype(float).std().replace(0, 1)

print("Train mean:")
display(train_mean)

print("Train std:")
display(train_std)

Train mean:

pos_x        0.343933
pos_y        0.396131
distance     0.540083
distance2    0.311916
distance3    0.193269
sin_angle    0.744473
cos_angle    0.625777
pos_x2       0.141736
pos_y2       0.170180
pos_x3       0.069200
pos_y3       0.078257
pos_xy       0.137329
unit_x       0.625777
unit_y       0.744473
dtype: float64

Train std:

pos_x        0.153132
pos_y        0.115162
distance     0.142230
distance2    0.177328
distance3    0.181966
sin_angle    0.161494
cos_angle    0.167600
pos_x2       0.137104
pos_y2       0.098119
pos_x3       0.107203
pos_y3       0.076458
pos_xy       0.082293
unit_x       0.167600
unit_y       0.161494
dtype: float64

correct dataset

In [106]:
class PositionBeamDataset(Dataset):
    def __init__(self, df, feature_cols, label_col, mean, std, label_to_id):
        self.df = df.reset_index(drop=True).copy()
        self.feature_cols = feature_cols
        self.label_col = label_col
        self.mean = mean
        self.std = std
        self.label_to_id = label_to_id

        x = self.df[self.feature_cols].astype(float)
        x = (x - self.mean) / self.std

        y_raw = self.df[self.label_col].values
        y = [self.label_to_id[int(v)] for v in y_raw]

        self.x = torch.tensor(x.values, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

correct dataloader

In [107]:
batch_size = 64

dataset_pos_train = PositionBeamDataset(train_pos_df, feature_cols, label_col, train_mean, train_std, label_to_id)
dataset_pos_val   = PositionBeamDataset(val_pos_df, feature_cols, label_col, train_mean, train_std, label_to_id)
dataset_pos_test  = PositionBeamDataset(test_pos_df, feature_cols, label_col, train_mean, train_std, label_to_id)

train_loader_pos = DataLoader(dataset_pos_train, batch_size=batch_size, shuffle=True)
val_loader_pos   = DataLoader(dataset_pos_val, batch_size=batch_size, shuffle=False)
test_loader_pos  = DataLoader(dataset_pos_test, batch_size=batch_size, shuffle=False)

x_batch, y_batch = next(iter(train_loader_pos))

print("x_batch shape:", x_batch.shape)
print("y_batch shape:", y_batch.shape)
print("First x:", x_batch[:5])
print("First mapped y:", y_batch[:10])

input_dim = x_batch.shape[1]
num_classes = num_classes_pos

print("input_dim:", input_dim)
print("num_classes:", num_classes)

x_batch shape: torch.Size([64, 14])
y_batch shape: torch.Size([64])
First x: tensor([[ 0.6498,  0.5952,  0.7187,  0.5675,  0.3941, -0.1302,  0.3854,  0.4004,
          0.4662,  0.1678,  0.2887,  0.8351,  0.3854, -0.1302],
        [-0.8635, -1.5201, -1.6452, -1.2306, -0.9045, -0.1376,  0.3929, -0.7069,
         -1.2363, -0.5570, -0.8822, -1.1001,  0.3929, -0.1376],
        [-0.5376, -2.0916, -1.6584, -1.2371, -0.9074, -1.4496,  1.3973, -0.5346,
         -1.4887, -0.4785, -0.9746, -1.1752,  1.3973, -1.4496],
        [-0.4353,  1.6313,  0.7480,  0.5978,  0.4226,  0.9838, -1.1747, -0.4730,
          1.7414, -0.4467,  1.5814,  0.2989, -1.1747,  0.9838],
        [-0.4361, -0.0519, -0.4324, -0.4674, -0.4597,  0.4382, -0.2784, -0.4735,
         -0.1830, -0.4469, -0.2468, -0.3548, -0.2784,  0.4382]])
First mapped y: tensor([15,  2,  0, 24, 13, 18, 13, 28,  9, 15])
input_dim: 14
num_classes: 29

In [108]:
x_batch, y_batch = next(iter(train_loader_pos))

print("x_batch shape:", x_batch.shape)
print("y_batch shape:", y_batch.shape)
print("First x:", x_batch[:5])
print("First y:", y_batch[:10])

input_dim = x_batch.shape[1]
num_classes = 64

print("input_dim:", input_dim)
print("num_classes:", num_classes)

x_batch shape: torch.Size([64, 14])
y_batch shape: torch.Size([64])
First x: tensor([[-0.8435,  0.1222, -0.5418, -0.5500, -0.5166,  0.8759, -0.9663, -0.6974,
         -0.0195, -0.5531, -0.1208, -0.5983, -0.9663,  0.8759],
        [-0.9343,  0.5208, -0.2933, -0.3583, -0.3819,  1.0571, -1.3290, -0.7395,
          0.3858, -0.5699,  0.2175, -0.5555, -1.3290,  1.0571],
        [ 0.0867,  0.1678,  0.0550, -0.0661, -0.1582,  0.0854,  0.1561, -0.1031,
          0.0247, -0.2204, -0.0856,  0.1346,  0.1561,  0.0854],
        [-0.8091,  0.7717, -0.0527, -0.1594, -0.2319,  1.0290, -1.2686, -0.6806,
          0.6629, -0.5461,  0.4686, -0.3720, -1.2686,  1.0290],
        [ 1.2700,  0.5976,  1.2044,  1.0949,  0.9163, -0.5628,  0.7820,  1.0806,
          0.4688,  0.8104,  0.2911,  1.3732,  0.7820, -0.5628]])
First y: tensor([14, 18, 15, 20, 15, 11, 19, 15, 14, 13])
input_dim: 14
num_classes: 64

4 layer mlp

newly

In [109]:
class FourLayerMLP(nn.Module):
    def __init__(self, input_dim, num_classes=64, hidden_dims=(512, 256, 128, 64), dropout=0.10):
        super().__init__()
        h1, h2, h3, h4 = hidden_dims

        self.net = nn.Sequential(
            nn.Linear(input_dim, h1),
            nn.BatchNorm1d(h1),
            nn.GELU(),
            nn.Dropout(dropout),

            nn.Linear(h1, h2),
            nn.BatchNorm1d(h2),
            nn.GELU(),
            nn.Dropout(dropout),

            nn.Linear(h2, h3),
            nn.BatchNorm1d(h3),
            nn.GELU(),
            nn.Dropout(dropout),

            nn.Linear(h3, h4),
            nn.BatchNorm1d(h4),
            nn.GELU(),

            nn.Linear(h4, num_classes)
        )

    def forward(self, x):
        return self.net(x)

In [110]:
model_name = "mlp4"

set_seed(42)

model_pos = build_position_model(
    model_name,
    input_dim=input_dim,
    num_classes=num_classes_pos
)

save_path = f"/content/drive/MyDrive/best_position_{model_name}_engineered_v2.pth"

history_pos = train_position_model(
    model=model_pos,
    train_loader=train_loader_pos,
    val_loader=val_loader_pos,
    device=device,
    epochs=100,
    lr=3e-4,
    weight_decay=1e-6,
    milestones=(50, 80),
    save_path=save_path
)

model_pos_eval = build_position_model(
    model_name,
    input_dim=input_dim,
    num_classes=num_classes_pos
)

model_pos_eval.load_state_dict(torch.load(save_path, map_location=device))

test_metrics_pos = evaluate_topk_pos(
    model_pos_eval,
    test_loader_pos,
    device,
    ks=(1, 2, 3, 5)
)

print(f"{model_name} Test metrics:", test_metrics_pos)

Epoch 01 | Train Loss: 2.6288 | Top1: 45.96 | Top2: 69.79 | Top3: 78.45 | Top5: 88.00
Saved best model
Epoch 02 | Train Loss: 1.9386 | Top1: 50.41 | Top2: 72.98 | Top3: 82.76 | Top5: 91.42
Saved best model
Epoch 03 | Train Loss: 1.6399 | Top1: 53.13 | Top2: 75.00 | Top3: 85.42 | Top5: 92.62
Saved best model
Epoch 04 | Train Loss: 1.5035 | Top1: 53.54 | Top2: 74.94 | Top3: 86.33 | Top5: 94.03
Saved best model
Epoch 05 | Train Loss: 1.4330 | Top1: 55.50 | Top2: 78.02 | Top3: 87.85 | Top5: 94.29
Saved best model
Epoch 06 | Train Loss: 1.3938 | Top1: 55.15 | Top2: 77.25 | Top3: 87.94 | Top5: 94.96
Epoch 07 | Train Loss: 1.3572 | Top1: 55.15 | Top2: 78.13 | Top3: 88.44 | Top5: 95.46
Epoch 08 | Train Loss: 1.3420 | Top1: 56.24 | Top2: 77.37 | Top3: 87.79 | Top5: 95.40
Saved best model
Epoch 09 | Train Loss: 1.3172 | Top1: 57.17 | Top2: 78.83 | Top3: 88.64 | Top5: 95.73
Saved best model
Epoch 10 | Train Loss: 1.2999 | Top1: 54.92 | Top2: 77.28 | Top3: 88.88 | Top5: 95.35
Epoch 11 | Train Loss: 1.2906 | Top1: 56.44 | Top2: 78.69 | Top3: 88.85 | Top5: 96.31
Epoch 12 | Train Loss: 1.2740 | Top1: 56.24 | Top2: 77.87 | Top3: 88.70 | Top5: 96.02
Epoch 13 | Train Loss: 1.2671 | Top1: 58.46 | Top2: 79.65 | Top3: 89.29 | Top5: 96.08
Saved best model
Epoch 14 | Train Loss: 1.2590 | Top1: 58.67 | Top2: 80.15 | Top3: 89.67 | Top5: 96.87
Saved best model
Epoch 15 | Train Loss: 1.2488 | Top1: 56.41 | Top2: 77.93 | Top3: 89.31 | Top5: 96.37
Epoch 16 | Train Loss: 1.2336 | Top1: 58.37 | Top2: 79.27 | Top3: 89.90 | Top5: 96.37
Epoch 17 | Train Loss: 1.2271 | Top1: 57.96 | Top2: 79.07 | Top3: 89.43 | Top5: 96.52
Epoch 18 | Train Loss: 1.2211 | Top1: 57.29 | Top2: 78.19 | Top3: 89.46 | Top5: 96.96
Epoch 19 | Train Loss: 1.2217 | Top1: 57.29 | Top2: 78.13 | Top3: 89.29 | Top5: 96.96
Epoch 20 | Train Loss: 1.2199 | Top1: 58.34 | Top2: 79.13 | Top3: 89.75 | Top5: 96.96
Epoch 21 | Train Loss: 1.2053 | Top1: 58.31 | Top2: 80.04 | Top3: 90.37 | Top5: 97.28
Epoch 22 | Train Loss: 1.2022 | Top1: 58.43 | Top2: 79.86 | Top3: 90.28 | Top5: 96.90
Epoch 23 | Train Loss: 1.1902 | Top1: 59.78 | Top2: 80.12 | Top3: 90.19 | Top5: 97.04
Saved best model
Epoch 24 | Train Loss: 1.2060 | Top1: 58.40 | Top2: 80.21 | Top3: 90.63 | Top5: 97.10
Epoch 25 | Train Loss: 1.1952 | Top1: 58.93 | Top2: 79.89 | Top3: 90.13 | Top5: 97.48
Epoch 26 | Train Loss: 1.1857 | Top1: 59.25 | Top2: 80.27 | Top3: 90.16 | Top5: 97.34
Epoch 27 | Train Loss: 1.1747 | Top1: 59.43 | Top2: 80.47 | Top3: 91.01 | Top5: 97.10
Epoch 28 | Train Loss: 1.1622 | Top1: 59.89 | Top2: 80.39 | Top3: 90.60 | Top5: 97.60
Saved best model
Epoch 29 | Train Loss: 1.1745 | Top1: 59.51 | Top2: 80.62 | Top3: 90.40 | Top5: 97.04
Epoch 30 | Train Loss: 1.1677 | Top1: 60.25 | Top2: 80.85 | Top3: 90.46 | Top5: 97.34
Saved best model
Epoch 31 | Train Loss: 1.1533 | Top1: 59.84 | Top2: 81.24 | Top3: 90.57 | Top5: 97.22
Epoch 32 | Train Loss: 1.1503 | Top1: 59.69 | Top2: 80.91 | Top3: 90.46 | Top5: 97.16
Epoch 33 | Train Loss: 1.1467 | Top1: 59.66 | Top2: 80.47 | Top3: 90.54 | Top5: 96.96
Epoch 34 | Train Loss: 1.1673 | Top1: 60.28 | Top2: 81.38 | Top3: 90.72 | Top5: 97.54
Saved best model
Epoch 35 | Train Loss: 1.1558 | Top1: 59.81 | Top2: 80.77 | Top3: 90.93 | Top5: 97.37
Epoch 36 | Train Loss: 1.1377 | Top1: 60.71 | Top2: 81.09 | Top3: 91.19 | Top5: 97.57
Saved best model
Epoch 37 | Train Loss: 1.1342 | Top1: 60.60 | Top2: 80.91 | Top3: 90.69 | Top5: 97.69
Epoch 38 | Train Loss: 1.1398 | Top1: 60.63 | Top2: 81.38 | Top3: 91.22 | Top5: 97.75
Epoch 39 | Train Loss: 1.1386 | Top1: 58.69 | Top2: 79.45 | Top3: 89.90 | Top5: 97.39
Epoch 40 | Train Loss: 1.1263 | Top1: 60.69 | Top2: 81.41 | Top3: 91.36 | Top5: 97.72
Epoch 41 | Train Loss: 1.1290 | Top1: 60.57 | Top2: 82.29 | Top3: 91.60 | Top5: 97.69
Epoch 42 | Train Loss: 1.1320 | Top1: 60.33 | Top2: 81.06 | Top3: 91.01 | Top5: 97.83
Epoch 43 | Train Loss: 1.1105 | Top1: 61.86 | Top2: 82.87 | Top3: 91.31 | Top5: 97.80
Saved best model
Epoch 44 | Train Loss: 1.1371 | Top1: 59.25 | Top2: 80.97 | Top3: 90.69 | Top5: 97.83
Epoch 45 | Train Loss: 1.1307 | Top1: 61.18 | Top2: 82.96 | Top3: 91.60 | Top5: 97.63
Epoch 46 | Train Loss: 1.1213 | Top1: 61.18 | Top2: 82.52 | Top3: 91.51 | Top5: 97.78
Epoch 47 | Train Loss: 1.1234 | Top1: 60.57 | Top2: 81.59 | Top3: 91.31 | Top5: 97.39
Epoch 48 | Train Loss: 1.1190 | Top1: 59.43 | Top2: 81.35 | Top3: 91.51 | Top5: 97.66
Epoch 49 | Train Loss: 1.1153 | Top1: 59.89 | Top2: 81.26 | Top3: 91.19 | Top5: 97.95
Epoch 50 | Train Loss: 1.1135 | Top1: 60.36 | Top2: 81.59 | Top3: 91.54 | Top5: 97.98
Epoch 51 | Train Loss: 1.0956 | Top1: 60.83 | Top2: 81.50 | Top3: 91.92 | Top5: 97.78
Epoch 52 | Train Loss: 1.0852 | Top1: 60.86 | Top2: 81.50 | Top3: 91.98 | Top5: 97.89
Epoch 53 | Train Loss: 1.0817 | Top1: 60.60 | Top2: 82.23 | Top3: 91.66 | Top5: 97.86
Epoch 54 | Train Loss: 1.0893 | Top1: 61.18 | Top2: 81.91 | Top3: 91.77 | Top5: 97.98
Epoch 55 | Train Loss: 1.0829 | Top1: 60.48 | Top2: 80.94 | Top3: 91.19 | Top5: 97.69
Epoch 56 | Train Loss: 1.0873 | Top1: 61.48 | Top2: 82.32 | Top3: 91.83 | Top5: 97.78
Epoch 57 | Train Loss: 1.0843 | Top1: 61.48 | Top2: 82.23 | Top3: 91.89 | Top5: 97.80
Epoch 58 | Train Loss: 1.0768 | Top1: 60.86 | Top2: 81.44 | Top3: 91.69 | Top5: 97.78
Epoch 59 | Train Loss: 1.0738 | Top1: 60.36 | Top2: 82.35 | Top3: 91.60 | Top5: 98.01
Epoch 60 | Train Loss: 1.0808 | Top1: 60.71 | Top2: 81.65 | Top3: 91.51 | Top5: 97.83
Epoch 61 | Train Loss: 1.0885 | Top1: 60.63 | Top2: 81.56 | Top3: 91.22 | Top5: 97.92
Epoch 62 | Train Loss: 1.0733 | Top1: 61.53 | Top2: 82.76 | Top3: 92.21 | Top5: 97.78
Epoch 63 | Train Loss: 1.0787 | Top1: 61.07 | Top2: 82.38 | Top3: 92.21 | Top5: 97.78
Epoch 64 | Train Loss: 1.0762 | Top1: 61.12 | Top2: 82.14 | Top3: 91.74 | Top5: 97.83
Epoch 65 | Train Loss: 1.0775 | Top1: 61.39 | Top2: 82.17 | Top3: 91.95 | Top5: 97.83
Epoch 66 | Train Loss: 1.0691 | Top1: 61.07 | Top2: 82.29 | Top3: 91.89 | Top5: 97.75
Epoch 67 | Train Loss: 1.0815 | Top1: 61.71 | Top2: 82.96 | Top3: 91.74 | Top5: 97.69
Epoch 68 | Train Loss: 1.0818 | Top1: 59.51 | Top2: 80.97 | Top3: 91.22 | Top5: 97.92
Epoch 69 | Train Loss: 1.0732 | Top1: 61.09 | Top2: 83.05 | Top3: 91.92 | Top5: 97.83
Epoch 70 | Train Loss: 1.0788 | Top1: 61.45 | Top2: 81.79 | Top3: 92.01 | Top5: 97.89
Epoch 71 | Train Loss: 1.0759 | Top1: 61.21 | Top2: 82.26 | Top3: 92.10 | Top5: 97.92
Epoch 72 | Train Loss: 1.0752 | Top1: 61.83 | Top2: 82.82 | Top3: 92.21 | Top5: 97.78
Epoch 73 | Train Loss: 1.0752 | Top1: 61.59 | Top2: 83.34 | Top3: 91.74 | Top5: 97.80
Epoch 74 | Train Loss: 1.0692 | Top1: 61.27 | Top2: 82.58 | Top3: 91.92 | Top5: 97.78
Epoch 75 | Train Loss: 1.0747 | Top1: 61.89 | Top2: 82.38 | Top3: 91.92 | Top5: 97.80
Saved best model
Epoch 76 | Train Loss: 1.0689 | Top1: 60.30 | Top2: 81.82 | Top3: 91.45 | Top5: 97.83
Epoch 77 | Train Loss: 1.0734 | Top1: 61.86 | Top2: 83.08 | Top3: 91.98 | Top5: 97.75
Epoch 78 | Train Loss: 1.0677 | Top1: 61.91 | Top2: 83.20 | Top3: 91.98 | Top5: 97.89
Saved best model
Epoch 79 | Train Loss: 1.0726 | Top1: 59.40 | Top2: 80.71 | Top3: 90.93 | Top5: 97.80
Epoch 80 | Train Loss: 1.0670 | Top1: 61.65 | Top2: 82.79 | Top3: 92.21 | Top5: 97.80
Epoch 81 | Train Loss: 1.0671 | Top1: 60.83 | Top2: 81.59 | Top3: 91.89 | Top5: 97.78
Epoch 82 | Train Loss: 1.0683 | Top1: 61.21 | Top2: 81.91 | Top3: 92.15 | Top5: 97.80
Epoch 83 | Train Loss: 1.0732 | Top1: 61.27 | Top2: 82.14 | Top3: 91.86 | Top5: 97.95
Epoch 84 | Train Loss: 1.0646 | Top1: 61.53 | Top2: 82.46 | Top3: 92.13 | Top5: 97.86
Epoch 85 | Train Loss: 1.0719 | Top1: 61.21 | Top2: 82.52 | Top3: 92.10 | Top5: 97.89
Epoch 86 | Train Loss: 1.0610 | Top1: 61.18 | Top2: 82.46 | Top3: 91.92 | Top5: 98.04
Epoch 87 | Train Loss: 1.0704 | Top1: 60.74 | Top2: 82.35 | Top3: 91.57 | Top5: 97.92
Epoch 88 | Train Loss: 1.0697 | Top1: 61.15 | Top2: 82.73 | Top3: 91.86 | Top5: 97.80
Epoch 89 | Train Loss: 1.0667 | Top1: 61.62 | Top2: 82.20 | Top3: 91.89 | Top5: 97.78
Epoch 90 | Train Loss: 1.0730 | Top1: 61.83 | Top2: 82.67 | Top3: 92.04 | Top5: 97.78
Epoch 91 | Train Loss: 1.0661 | Top1: 61.24 | Top2: 82.73 | Top3: 92.15 | Top5: 97.92
Epoch 92 | Train Loss: 1.0617 | Top1: 61.97 | Top2: 82.90 | Top3: 92.18 | Top5: 97.80
Saved best model
Epoch 93 | Train Loss: 1.0545 | Top1: 61.21 | Top2: 82.35 | Top3: 92.04 | Top5: 98.01
Epoch 94 | Train Loss: 1.0661 | Top1: 60.01 | Top2: 82.03 | Top3: 91.86 | Top5: 97.98
Epoch 95 | Train Loss: 1.0688 | Top1: 61.48 | Top2: 82.61 | Top3: 91.89 | Top5: 97.89
Epoch 96 | Train Loss: 1.0672 | Top1: 61.42 | Top2: 82.38 | Top3: 91.89 | Top5: 97.95
Epoch 97 | Train Loss: 1.0763 | Top1: 61.30 | Top2: 82.73 | Top3: 91.86 | Top5: 97.89
Epoch 98 | Train Loss: 1.0685 | Top1: 61.59 | Top2: 82.82 | Top3: 91.83 | Top5: 97.86
Epoch 99 | Train Loss: 1.0581 | Top1: 61.04 | Top2: 82.41 | Top3: 91.72 | Top5: 97.89
Epoch 100 | Train Loss: 1.0772 | Top1: 62.09 | Top2: 82.87 | Top3: 91.95 | Top5: 97.78
Saved best model
mlp4 Test metrics: {'top1': 59.701492537313435, 'top2': 82.61633011413521, 'top3': 92.44951712028094, 'top5': 98.24407374890255}

In [111]:
class FourLayerMLP(nn.Module):
    def __init__(self, input_dim, num_classes=64, hidden_dims=(128, 256, 128, 64), dropout=0.2):
        super().__init__()
        h1, h2, h3, h4 = hidden_dims

        self.net = nn.Sequential(
            nn.Linear(input_dim, h1),
            nn.BatchNorm1d(h1),
            nn.ReLU(),
            nn.Dropout(dropout),

            nn.Linear(h1, h2),
            nn.BatchNorm1d(h2),
            nn.ReLU(),
            nn.Dropout(dropout),

            nn.Linear(h2, h3),
            nn.BatchNorm1d(h3),
            nn.ReLU(),
            nn.Dropout(dropout),

            nn.Linear(h3, h4),
            nn.BatchNorm1d(h4),
            nn.ReLU(),

            nn.Linear(h4, num_classes)
        )

    def forward(self, x):
        return self.net(x)

ann

In [112]:
class SimpleANN(nn.Module):
    def __init__(self, input_dim, num_classes=64, hidden_dim=128, dropout=0.2):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),

            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),

            nn.Linear(hidden_dim, num_classes)
        )

    def forward(self, x):
        return self.net(x)

ann + attention

In [115]:
class ANNWithAttention(nn.Module):
    def __init__(self, input_dim, num_classes=64, hidden_dim=128, dropout=0.2):
        super().__init__()

        self.attn = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, input_dim),
            nn.Softmax(dim=1)
        )

        self.classifier = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.GeLU(),
            nn.Dropout(dropout),

            nn.Linear(hidden_dim, hidden_dim),
            nn.GeLU(),
            nn.Dropout(dropout),

            nn.Linear(hidden_dim, num_classes)
        )

    def forward(self, x):
        weights = self.attn(x)
        x_weighted = x * weights
        return self.classifier(x_weighted)

rnn

In [116]:
class PositionRNN(nn.Module):
    def __init__(self, input_dim, num_classes=64, hidden_dim=64, num_layers=2, dropout=0.1):
        super().__init__()

        self.rnn = nn.RNN(
            input_size=1,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0
        )

        self.fc = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        x_seq = x.unsqueeze(-1)
        out, h = self.rnn(x_seq)
        last = out[:, -1, :]
        return self.fc(last)

lstm

In [117]:
class PositionLSTM(nn.Module):
    def __init__(self, input_dim, num_classes=64, hidden_dim=64, num_layers=2, dropout=0.1):
        super().__init__()

        self.lstm = nn.LSTM(
            input_size=1,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0
        )

        self.fc = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        x_seq = x.unsqueeze(-1)
        out, (h, c) = self.lstm(x_seq)
        last = out[:, -1, :]
        return self.fc(last)

top - k evaluation

In [118]:
def evaluate_topk_pos(model, loader, device, ks=(1, 2, 3, 5)):
    model.eval()
    total = 0
    correct = {k: 0 for k in ks}

    with torch.no_grad():
        for x, labels in loader:
            x = x.to(device)
            labels = labels.to(device)

            outputs = model(x)

            max_k = max(ks)
            _, pred = torch.topk(outputs, k=max_k, dim=1)
            pred = pred.t()

            total += labels.size(0)

            for k in ks:
                correct[k] += pred[:k].eq(labels.view(1, -1)).sum().item()

    return {f"top{k}": 100.0 * correct[k] / total for k in ks}

trainer

In [119]:
def train_position_model(
    model,
    train_loader,
    val_loader,
    device,
    epochs=50,
    lr=1e-3,
    weight_decay=1e-4,
    milestones=(20, 35),
    save_path="/content/drive/MyDrive/best_position_model.pth"
):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    scheduler = optim.lr_scheduler.MultiStepLR(optimizer, milestones=list(milestones), gamma=0.1)

    best_top1 = -1
    history = []

    for epoch in range(1, epochs + 1):
        model.train()
        running_loss = 0.0
        total_train = 0

        for x, labels in train_loader:
            x = x.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()
            outputs = model(x)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            bs = labels.size(0)
            running_loss += loss.item() * bs
            total_train += bs

        scheduler.step()

        train_loss = running_loss / total_train
        val_metrics = evaluate_topk_pos(model, val_loader, device, ks=(1, 2, 3, 5))

        row = {
            "epoch": epoch,
            "train_loss": train_loss,
            **val_metrics
        }
        history.append(row)

        print(
            f"Epoch {epoch:02d} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Top1: {val_metrics['top1']:.2f} | "
            f"Top2: {val_metrics['top2']:.2f} | "
            f"Top3: {val_metrics['top3']:.2f} | "
            f"Top5: {val_metrics['top5']:.2f}"
        )

        if val_metrics["top1"] > best_top1:
            best_top1 = val_metrics["top1"]
            torch.save(copy.deepcopy(model.state_dict()), save_path)
            print("Saved best model")

    return pd.DataFrame(history)

model builder

In [120]:
def build_position_model(model_name, input_dim, num_classes=num_classes_pos):
    if model_name == "mlp4":
        return FourLayerMLP(input_dim=input_dim, num_classes=num_classes).to(device)

    elif model_name == "ann":
        return SimpleANN(input_dim=input_dim, num_classes=num_classes).to(device)

    elif model_name == "ann_attention":
        return ANNWithAttention(input_dim=input_dim, num_classes=num_classes).to(device)

    elif model_name == "rnn":
        return PositionRNN(input_dim=input_dim, num_classes=num_classes).to(device)

    elif model_name == "lstm":
        return PositionLSTM(input_dim=input_dim, num_classes=num_classes).to(device)

    else:
        raise ValueError("Unknown model_name")

run all the models

In [121]:
position_model_names = [
    "mlp4",
    "ann",
    "ann_attention",
    "rnn",
    "lstm"
]

all_position_histories = {}
pos_results = []

for model_name in position_model_names:
    print("\n" + "="*80)
    print(f"Training Position Model: {model_name}")
    print("="*80)

    set_seed(42)

    model_pos = build_position_model(
        model_name,
        input_dim=input_dim,
        num_classes=num_classes_pos
    )

    save_path = f"/content/drive/MyDrive/best_position_{model_name}.pth"

    history_pos = train_position_model(
        model=model_pos,
        train_loader=train_loader_pos,
        val_loader=val_loader_pos,
        device=device,
        epochs=100,
        lr=1e-3,
        weight_decay=1e-4,
        milestones=(20, 35),
        save_path=save_path
    )

    all_position_histories[model_name] = history_pos

    model_pos_eval = build_position_model(
        model_name,
        input_dim=input_dim,
        num_classes=num_classes_pos
    )

    model_pos_eval.load_state_dict(torch.load(save_path, map_location=device))

    test_metrics_pos = evaluate_topk_pos(model_pos_eval, test_loader_pos, device, ks=(1, 2, 3, 5))

    print(f"{model_name} Test metrics:", test_metrics_pos)

    pos_results.append({
        "Model": model_name,
        "Top-1": test_metrics_pos["top1"],
        "Top-2": test_metrics_pos["top2"],
        "Top-3": test_metrics_pos["top3"],
        "Top-5": test_metrics_pos["top5"],
    })

    del model_pos
    del model_pos_eval
    torch.cuda.empty_cache()

pos_results_df = pd.DataFrame(pos_results)
pos_results_df

================================================================================
Training Position Model: mlp4
================================================================================
Epoch 01 | Train Loss: 2.1800 | Top1: 47.22 | Top2: 70.78 | Top3: 82.06 | Top5: 91.28
Saved best model
Epoch 02 | Train Loss: 1.6049 | Top1: 51.73 | Top2: 74.03 | Top3: 85.74 | Top5: 93.59
Saved best model
Epoch 03 | Train Loss: 1.4920 | Top1: 52.84 | Top2: 76.02 | Top3: 87.21 | Top5: 94.32
Saved best model
Epoch 04 | Train Loss: 1.4355 | Top1: 54.19 | Top2: 76.43 | Top3: 87.03 | Top5: 94.70
Saved best model
Epoch 05 | Train Loss: 1.4066 | Top1: 53.83 | Top2: 75.56 | Top3: 86.91 | Top5: 94.96
Epoch 06 | Train Loss: 1.3851 | Top1: 56.06 | Top2: 77.84 | Top3: 87.82 | Top5: 95.32
Saved best model
Epoch 07 | Train Loss: 1.3616 | Top1: 54.19 | Top2: 76.76 | Top3: 88.09 | Top5: 95.81
Epoch 08 | Train Loss: 1.3692 | Top1: 55.97 | Top2: 77.96 | Top3: 88.26 | Top5: 95.81
Epoch 09 | Train Loss: 1.3495 | Top1: 57.61 | Top2: 79.68 | Top3: 89.64 | Top5: 95.81
Saved best model
Epoch 10 | Train Loss: 1.3347 | Top1: 57.11 | Top2: 79.10 | Top3: 88.38 | Top5: 96.02
Epoch 11 | Train Loss: 1.3160 | Top1: 56.38 | Top2: 78.16 | Top3: 88.29 | Top5: 95.87
Epoch 12 | Train Loss: 1.3106 | Top1: 55.06 | Top2: 77.69 | Top3: 87.50 | Top5: 95.84
Epoch 13 | Train Loss: 1.3055 | Top1: 55.56 | Top2: 77.66 | Top3: 88.96 | Top5: 96.40
Epoch 14 | Train Loss: 1.3195 | Top1: 56.24 | Top2: 77.66 | Top3: 88.96 | Top5: 96.08
Epoch 15 | Train Loss: 1.3012 | Top1: 57.23 | Top2: 79.57 | Top3: 89.37 | Top5: 96.69
Epoch 16 | Train Loss: 1.3043 | Top1: 57.35 | Top2: 78.63 | Top3: 89.99 | Top5: 96.63
Epoch 17 | Train Loss: 1.2667 | Top1: 56.82 | Top2: 78.07 | Top3: 89.02 | Top5: 96.25
Epoch 18 | Train Loss: 1.2690 | Top1: 56.06 | Top2: 76.46 | Top3: 87.91 | Top5: 95.61
Epoch 19 | Train Loss: 1.2745 | Top1: 55.80 | Top2: 78.28 | Top3: 89.87 | Top5: 96.46
Epoch 20 | Train Loss: 1.2672 | Top1: 57.76 | Top2: 79.19 | Top3: 89.29 | Top5: 96.43
Saved best model
Epoch 21 | Train Loss: 1.2502 | Top1: 60.36 | Top2: 80.62 | Top3: 90.22 | Top5: 96.84
Saved best model
Epoch 22 | Train Loss: 1.2378 | Top1: 58.64 | Top2: 79.13 | Top3: 89.93 | Top5: 96.81
Epoch 23 | Train Loss: 1.2373 | Top1: 59.19 | Top2: 79.95 | Top3: 89.96 | Top5: 96.66
Epoch 24 | Train Loss: 1.2213 | Top1: 57.03 | Top2: 78.31 | Top3: 89.31 | Top5: 96.52
Epoch 25 | Train Loss: 1.2273 | Top1: 59.51 | Top2: 79.92 | Top3: 89.87 | Top5: 96.66
Epoch 26 | Train Loss: 1.2199 | Top1: 57.35 | Top2: 79.01 | Top3: 89.96 | Top5: 96.63
Epoch 27 | Train Loss: 1.2317 | Top1: 56.79 | Top2: 78.16 | Top3: 89.23 | Top5: 96.57
Epoch 28 | Train Loss: 1.2130 | Top1: 59.05 | Top2: 80.24 | Top3: 90.08 | Top5: 96.96
Epoch 29 | Train Loss: 1.2165 | Top1: 60.54 | Top2: 80.59 | Top3: 89.99 | Top5: 96.93
Saved best model
Epoch 30 | Train Loss: 1.2181 | Top1: 58.99 | Top2: 79.33 | Top3: 89.84 | Top5: 96.75
Epoch 31 | Train Loss: 1.2103 | Top1: 60.22 | Top2: 80.59 | Top3: 90.02 | Top5: 97.07
Epoch 32 | Train Loss: 1.2122 | Top1: 60.45 | Top2: 80.88 | Top3: 90.05 | Top5: 97.10
Epoch 33 | Train Loss: 1.2082 | Top1: 60.30 | Top2: 80.59 | Top3: 90.28 | Top5: 96.93
Epoch 34 | Train Loss: 1.2211 | Top1: 59.02 | Top2: 79.80 | Top3: 89.96 | Top5: 97.13
Epoch 35 | Train Loss: 1.1977 | Top1: 59.98 | Top2: 80.30 | Top3: 89.96 | Top5: 96.96
Epoch 36 | Train Loss: 1.2072 | Top1: 59.84 | Top2: 80.18 | Top3: 90.02 | Top5: 96.96
Epoch 37 | Train Loss: 1.2127 | Top1: 59.75 | Top2: 80.01 | Top3: 90.25 | Top5: 96.87
Epoch 38 | Train Loss: 1.2090 | Top1: 58.17 | Top2: 79.51 | Top3: 89.87 | Top5: 96.84
Epoch 39 | Train Loss: 1.2119 | Top1: 60.60 | Top2: 80.50 | Top3: 90.19 | Top5: 97.10
Saved best model
Epoch 40 | Train Loss: 1.2000 | Top1: 58.14 | Top2: 78.78 | Top3: 89.93 | Top5: 96.63
Epoch 41 | Train Loss: 1.2119 | Top1: 59.40 | Top2: 79.89 | Top3: 89.99 | Top5: 97.10
Epoch 42 | Train Loss: 1.2126 | Top1: 60.19 | Top2: 80.44 | Top3: 90.08 | Top5: 97.22
Epoch 43 | Train Loss: 1.2020 | Top1: 59.78 | Top2: 79.86 | Top3: 90.11 | Top5: 96.78
Epoch 44 | Train Loss: 1.2063 | Top1: 59.69 | Top2: 79.98 | Top3: 89.87 | Top5: 97.28
Epoch 45 | Train Loss: 1.1958 | Top1: 57.96 | Top2: 78.98 | Top3: 89.58 | Top5: 96.60
Epoch 46 | Train Loss: 1.2328 | Top1: 59.02 | Top2: 79.77 | Top3: 89.84 | Top5: 96.84
Epoch 47 | Train Loss: 1.2044 | Top1: 60.13 | Top2: 80.09 | Top3: 90.11 | Top5: 96.84
Epoch 48 | Train Loss: 1.2175 | Top1: 59.72 | Top2: 79.95 | Top3: 89.96 | Top5: 96.84
Epoch 49 | Train Loss: 1.2076 | Top1: 60.74 | Top2: 80.50 | Top3: 90.22 | Top5: 97.19
Saved best model
Epoch 50 | Train Loss: 1.1972 | Top1: 58.87 | Top2: 79.68 | Top3: 89.96 | Top5: 96.98
Epoch 51 | Train Loss: 1.2011 | Top1: 60.89 | Top2: 81.15 | Top3: 90.34 | Top5: 97.22
Saved best model
Epoch 52 | Train Loss: 1.1995 | Top1: 60.42 | Top2: 80.83 | Top3: 90.49 | Top5: 97.25
Epoch 53 | Train Loss: 1.2037 | Top1: 59.37 | Top2: 79.98 | Top3: 90.13 | Top5: 97.01
Epoch 54 | Train Loss: 1.2033 | Top1: 58.75 | Top2: 79.45 | Top3: 89.75 | Top5: 96.96
Epoch 55 | Train Loss: 1.2123 | Top1: 60.95 | Top2: 80.80 | Top3: 90.22 | Top5: 97.22
Saved best model
Epoch 56 | Train Loss: 1.2020 | Top1: 60.25 | Top2: 80.39 | Top3: 89.96 | Top5: 96.81
Epoch 57 | Train Loss: 1.2049 | Top1: 58.37 | Top2: 79.24 | Top3: 89.84 | Top5: 96.81
Epoch 58 | Train Loss: 1.2077 | Top1: 60.71 | Top2: 81.15 | Top3: 90.49 | Top5: 96.96
Epoch 59 | Train Loss: 1.2081 | Top1: 59.75 | Top2: 80.21 | Top3: 90.19 | Top5: 97.10
Epoch 60 | Train Loss: 1.2185 | Top1: 59.87 | Top2: 80.27 | Top3: 89.93 | Top5: 96.87
Epoch 61 | Train Loss: 1.2120 | Top1: 59.63 | Top2: 80.09 | Top3: 90.11 | Top5: 96.84
Epoch 62 | Train Loss: 1.1928 | Top1: 58.78 | Top2: 79.98 | Top3: 90.02 | Top5: 97.01
Epoch 63 | Train Loss: 1.2117 | Top1: 59.57 | Top2: 79.71 | Top3: 90.11 | Top5: 97.13
Epoch 64 | Train Loss: 1.2110 | Top1: 60.30 | Top2: 80.59 | Top3: 90.22 | Top5: 97.01
Epoch 65 | Train Loss: 1.2055 | Top1: 57.82 | Top2: 78.86 | Top3: 89.58 | Top5: 96.52
Epoch 66 | Train Loss: 1.2164 | Top1: 60.13 | Top2: 80.15 | Top3: 90.05 | Top5: 96.75
Epoch 67 | Train Loss: 1.2036 | Top1: 60.30 | Top2: 80.83 | Top3: 90.31 | Top5: 97.01
Epoch 68 | Train Loss: 1.2131 | Top1: 59.72 | Top2: 80.47 | Top3: 90.37 | Top5: 97.10
Epoch 69 | Train Loss: 1.2097 | Top1: 60.33 | Top2: 80.88 | Top3: 90.02 | Top5: 96.93
Epoch 70 | Train Loss: 1.2028 | Top1: 60.10 | Top2: 80.68 | Top3: 90.11 | Top5: 96.90
Epoch 71 | Train Loss: 1.1914 | Top1: 58.96 | Top2: 79.74 | Top3: 89.93 | Top5: 96.98
Epoch 72 | Train Loss: 1.2038 | Top1: 60.42 | Top2: 80.56 | Top3: 90.13 | Top5: 97.01
Epoch 73 | Train Loss: 1.2025 | Top1: 60.39 | Top2: 80.36 | Top3: 90.05 | Top5: 96.78
Epoch 74 | Train Loss: 1.2013 | Top1: 59.37 | Top2: 79.95 | Top3: 90.05 | Top5: 97.22
Epoch 75 | Train Loss: 1.1919 | Top1: 58.64 | Top2: 79.54 | Top3: 89.99 | Top5: 96.96
Epoch 76 | Train Loss: 1.1995 | Top1: 60.22 | Top2: 80.77 | Top3: 90.13 | Top5: 96.90
Epoch 77 | Train Loss: 1.2068 | Top1: 58.64 | Top2: 79.60 | Top3: 89.84 | Top5: 96.87
Epoch 78 | Train Loss: 1.1944 | Top1: 60.45 | Top2: 81.09 | Top3: 90.19 | Top5: 96.98
Epoch 79 | Train Loss: 1.1964 | Top1: 59.92 | Top2: 80.44 | Top3: 90.02 | Top5: 96.93
Epoch 80 | Train Loss: 1.2012 | Top1: 58.31 | Top2: 79.04 | Top3: 89.81 | Top5: 96.75
Epoch 81 | Train Loss: 1.2035 | Top1: 58.87 | Top2: 79.77 | Top3: 90.19 | Top5: 97.13
Epoch 82 | Train Loss: 1.2061 | Top1: 59.07 | Top2: 79.71 | Top3: 89.99 | Top5: 96.90
Epoch 83 | Train Loss: 1.1969 | Top1: 60.36 | Top2: 80.36 | Top3: 89.96 | Top5: 97.07
Epoch 84 | Train Loss: 1.2140 | Top1: 60.16 | Top2: 80.30 | Top3: 90.43 | Top5: 97.31
Epoch 85 | Train Loss: 1.2044 | Top1: 60.80 | Top2: 81.03 | Top3: 90.08 | Top5: 97.10
Epoch 86 | Train Loss: 1.1906 | Top1: 60.92 | Top2: 80.85 | Top3: 90.28 | Top5: 97.16
Epoch 87 | Train Loss: 1.1922 | Top1: 59.54 | Top2: 80.04 | Top3: 89.93 | Top5: 97.07
Epoch 88 | Train Loss: 1.2107 | Top1: 60.30 | Top2: 80.50 | Top3: 90.08 | Top5: 96.87
Epoch 89 | Train Loss: 1.2073 | Top1: 60.42 | Top2: 80.65 | Top3: 90.40 | Top5: 97.25
Epoch 90 | Train Loss: 1.2155 | Top1: 59.87 | Top2: 80.01 | Top3: 89.90 | Top5: 97.13
Epoch 91 | Train Loss: 1.2000 | Top1: 59.75 | Top2: 80.33 | Top3: 90.13 | Top5: 97.28
Epoch 92 | Train Loss: 1.2027 | Top1: 57.26 | Top2: 78.34 | Top3: 89.52 | Top5: 96.69
Epoch 93 | Train Loss: 1.2005 | Top1: 60.74 | Top2: 80.80 | Top3: 90.22 | Top5: 97.07
Epoch 94 | Train Loss: 1.1934 | Top1: 60.22 | Top2: 80.71 | Top3: 90.13 | Top5: 96.98
Epoch 95 | Train Loss: 1.2054 | Top1: 59.28 | Top2: 80.04 | Top3: 90.02 | Top5: 97.31
Epoch 96 | Train Loss: 1.1955 | Top1: 60.77 | Top2: 80.88 | Top3: 90.02 | Top5: 96.90
Epoch 97 | Train Loss: 1.1994 | Top1: 58.28 | Top2: 78.86 | Top3: 89.78 | Top5: 96.84
Epoch 98 | Train Loss: 1.1900 | Top1: 60.71 | Top2: 80.88 | Top3: 90.16 | Top5: 97.10
Epoch 99 | Train Loss: 1.1990 | Top1: 59.78 | Top2: 79.86 | Top3: 89.78 | Top5: 97.10
Epoch 100 | Train Loss: 1.1925 | Top1: 58.61 | Top2: 79.10 | Top3: 89.46 | Top5: 96.63
mlp4 Test metrics: {'top1': 58.472344161545216, 'top2': 79.89464442493416, 'top3': 90.60579455662862, 'top5': 97.36611062335382}

================================================================================
Training Position Model: ann
================================================================================
Epoch 01 | Train Loss: 2.3833 | Top1: 45.78 | Top2: 65.31 | Top3: 80.65 | Top5: 89.05
Saved best model
Epoch 02 | Train Loss: 1.5556 | Top1: 50.44 | Top2: 73.21 | Top3: 83.99 | Top5: 93.24
Saved best model
Epoch 03 | Train Loss: 1.4075 | Top1: 53.66 | Top2: 75.70 | Top3: 86.21 | Top5: 94.58
Saved best model
Epoch 04 | Train Loss: 1.3454 | Top1: 54.68 | Top2: 76.64 | Top3: 86.89 | Top5: 95.02
Saved best model
Epoch 05 | Train Loss: 1.3015 | Top1: 55.01 | Top2: 78.69 | Top3: 88.14 | Top5: 95.08
Saved best model
Epoch 06 | Train Loss: 1.2929 | Top1: 56.03 | Top2: 79.83 | Top3: 88.32 | Top5: 95.26
Saved best model
Epoch 07 | Train Loss: 1.2602 | Top1: 55.42 | Top2: 79.33 | Top3: 88.03 | Top5: 95.23
Epoch 08 | Train Loss: 1.2559 | Top1: 56.79 | Top2: 79.33 | Top3: 88.99 | Top5: 96.28
Saved best model
Epoch 09 | Train Loss: 1.2393 | Top1: 57.52 | Top2: 79.89 | Top3: 88.26 | Top5: 95.93
Saved best model
Epoch 10 | Train Loss: 1.2281 | Top1: 57.29 | Top2: 80.62 | Top3: 88.91 | Top5: 96.52
Epoch 11 | Train Loss: 1.2199 | Top1: 56.73 | Top2: 79.65 | Top3: 88.64 | Top5: 96.43
Epoch 12 | Train Loss: 1.2183 | Top1: 58.26 | Top2: 80.83 | Top3: 89.67 | Top5: 96.84
Saved best model
Epoch 13 | Train Loss: 1.2148 | Top1: 56.97 | Top2: 79.83 | Top3: 88.61 | Top5: 96.22
Epoch 14 | Train Loss: 1.2073 | Top1: 57.55 | Top2: 80.24 | Top3: 89.05 | Top5: 96.22
Epoch 15 | Train Loss: 1.1917 | Top1: 58.11 | Top2: 80.50 | Top3: 90.11 | Top5: 96.78
Epoch 16 | Train Loss: 1.1922 | Top1: 57.76 | Top2: 80.53 | Top3: 88.96 | Top5: 96.34
Epoch 17 | Train Loss: 1.1874 | Top1: 58.64 | Top2: 80.42 | Top3: 89.81 | Top5: 96.72
Saved best model
Epoch 18 | Train Loss: 1.1857 | Top1: 58.69 | Top2: 81.35 | Top3: 89.75 | Top5: 96.49
Saved best model
Epoch 19 | Train Loss: 1.1793 | Top1: 59.46 | Top2: 80.74 | Top3: 89.70 | Top5: 96.55
Saved best model
Epoch 20 | Train Loss: 1.1778 | Top1: 58.93 | Top2: 80.62 | Top3: 89.55 | Top5: 96.55
Epoch 21 | Train Loss: 1.1623 | Top1: 59.22 | Top2: 81.06 | Top3: 89.78 | Top5: 96.46
Epoch 22 | Train Loss: 1.1521 | Top1: 59.48 | Top2: 81.50 | Top3: 89.90 | Top5: 96.66
Saved best model
Epoch 23 | Train Loss: 1.1539 | Top1: 59.22 | Top2: 81.50 | Top3: 89.90 | Top5: 96.60
Epoch 24 | Train Loss: 1.1550 | Top1: 59.57 | Top2: 81.53 | Top3: 90.05 | Top5: 96.69
Saved best model
Epoch 25 | Train Loss: 1.1536 | Top1: 59.92 | Top2: 81.67 | Top3: 90.34 | Top5: 96.84
Saved best model
Epoch 26 | Train Loss: 1.1579 | Top1: 59.87 | Top2: 81.65 | Top3: 90.31 | Top5: 96.63
Epoch 27 | Train Loss: 1.1498 | Top1: 59.81 | Top2: 81.70 | Top3: 90.19 | Top5: 96.66
Epoch 28 | Train Loss: 1.1523 | Top1: 59.78 | Top2: 81.79 | Top3: 90.08 | Top5: 96.78
Epoch 29 | Train Loss: 1.1477 | Top1: 59.69 | Top2: 81.41 | Top3: 90.05 | Top5: 96.72
Epoch 30 | Train Loss: 1.1512 | Top1: 59.63 | Top2: 81.73 | Top3: 90.16 | Top5: 96.63
Epoch 31 | Train Loss: 1.1445 | Top1: 59.60 | Top2: 81.94 | Top3: 90.16 | Top5: 96.66
Epoch 32 | Train Loss: 1.1430 | Top1: 59.63 | Top2: 81.62 | Top3: 90.31 | Top5: 96.78
Epoch 33 | Train Loss: 1.1423 | Top1: 59.46 | Top2: 81.85 | Top3: 90.19 | Top5: 96.69
Epoch 34 | Train Loss: 1.1440 | Top1: 59.78 | Top2: 81.76 | Top3: 90.13 | Top5: 96.69
Epoch 35 | Train Loss: 1.1444 | Top1: 59.84 | Top2: 81.82 | Top3: 90.13 | Top5: 96.66
Epoch 36 | Train Loss: 1.1455 | Top1: 59.89 | Top2: 81.82 | Top3: 90.16 | Top5: 96.69
Epoch 37 | Train Loss: 1.1428 | Top1: 59.92 | Top2: 81.85 | Top3: 90.11 | Top5: 96.66
Epoch 38 | Train Loss: 1.1488 | Top1: 59.89 | Top2: 81.76 | Top3: 90.13 | Top5: 96.72
Epoch 39 | Train Loss: 1.1459 | Top1: 59.92 | Top2: 81.70 | Top3: 90.11 | Top5: 96.69
Epoch 40 | Train Loss: 1.1454 | Top1: 59.84 | Top2: 81.73 | Top3: 90.08 | Top5: 96.69
Epoch 41 | Train Loss: 1.1461 | Top1: 59.81 | Top2: 81.79 | Top3: 90.05 | Top5: 96.72
Epoch 42 | Train Loss: 1.1387 | Top1: 59.89 | Top2: 81.76 | Top3: 89.99 | Top5: 96.69
Epoch 43 | Train Loss: 1.1417 | Top1: 59.81 | Top2: 81.82 | Top3: 90.05 | Top5: 96.69
Epoch 44 | Train Loss: 1.1460 | Top1: 59.81 | Top2: 81.85 | Top3: 89.99 | Top5: 96.66
Epoch 45 | Train Loss: 1.1438 | Top1: 59.84 | Top2: 81.79 | Top3: 90.05 | Top5: 96.69
Epoch 46 | Train Loss: 1.1451 | Top1: 59.78 | Top2: 81.79 | Top3: 90.08 | Top5: 96.75
Epoch 47 | Train Loss: 1.1376 | Top1: 59.81 | Top2: 81.88 | Top3: 90.05 | Top5: 96.66
Epoch 48 | Train Loss: 1.1434 | Top1: 59.84 | Top2: 81.76 | Top3: 90.05 | Top5: 96.69
Epoch 49 | Train Loss: 1.1476 | Top1: 59.81 | Top2: 81.79 | Top3: 90.08 | Top5: 96.72
Epoch 50 | Train Loss: 1.1417 | Top1: 59.78 | Top2: 81.73 | Top3: 90.13 | Top5: 96.75
Epoch 51 | Train Loss: 1.1433 | Top1: 59.75 | Top2: 81.76 | Top3: 90.13 | Top5: 96.72
Epoch 52 | Train Loss: 1.1430 | Top1: 59.75 | Top2: 81.73 | Top3: 90.16 | Top5: 96.72
Epoch 53 | Train Loss: 1.1425 | Top1: 59.75 | Top2: 81.73 | Top3: 90.13 | Top5: 96.72
Epoch 54 | Train Loss: 1.1372 | Top1: 59.75 | Top2: 81.73 | Top3: 90.22 | Top5: 96.72
Epoch 55 | Train Loss: 1.1406 | Top1: 59.69 | Top2: 81.70 | Top3: 90.16 | Top5: 96.72
Epoch 56 | Train Loss: 1.1412 | Top1: 59.72 | Top2: 81.73 | Top3: 90.11 | Top5: 96.72
Epoch 57 | Train Loss: 1.1434 | Top1: 59.78 | Top2: 81.76 | Top3: 90.16 | Top5: 96.69
Epoch 58 | Train Loss: 1.1408 | Top1: 59.78 | Top2: 81.85 | Top3: 90.13 | Top5: 96.69
Epoch 59 | Train Loss: 1.1360 | Top1: 59.75 | Top2: 81.79 | Top3: 90.22 | Top5: 96.66
Epoch 60 | Train Loss: 1.1365 | Top1: 59.81 | Top2: 81.82 | Top3: 90.19 | Top5: 96.69
Epoch 61 | Train Loss: 1.1377 | Top1: 59.81 | Top2: 81.79 | Top3: 90.11 | Top5: 96.69
Epoch 62 | Train Loss: 1.1394 | Top1: 59.84 | Top2: 81.76 | Top3: 90.11 | Top5: 96.69
Epoch 63 | Train Loss: 1.1416 | Top1: 59.84 | Top2: 81.76 | Top3: 90.08 | Top5: 96.69
Epoch 64 | Train Loss: 1.1433 | Top1: 59.84 | Top2: 81.73 | Top3: 90.08 | Top5: 96.69
Epoch 65 | Train Loss: 1.1470 | Top1: 59.72 | Top2: 81.73 | Top3: 90.16 | Top5: 96.69
Epoch 66 | Train Loss: 1.1454 | Top1: 59.78 | Top2: 81.67 | Top3: 90.11 | Top5: 96.72
Epoch 67 | Train Loss: 1.1377 | Top1: 59.75 | Top2: 81.70 | Top3: 90.19 | Top5: 96.72
Epoch 68 | Train Loss: 1.1429 | Top1: 59.78 | Top2: 81.76 | Top3: 90.16 | Top5: 96.72
Epoch 69 | Train Loss: 1.1446 | Top1: 59.81 | Top2: 81.73 | Top3: 90.11 | Top5: 96.72
Epoch 70 | Train Loss: 1.1433 | Top1: 59.75 | Top2: 81.73 | Top3: 90.11 | Top5: 96.75
Epoch 71 | Train Loss: 1.1462 | Top1: 59.69 | Top2: 81.76 | Top3: 90.19 | Top5: 96.69
Epoch 72 | Train Loss: 1.1437 | Top1: 59.69 | Top2: 81.76 | Top3: 90.19 | Top5: 96.69
Epoch 73 | Train Loss: 1.1490 | Top1: 59.69 | Top2: 81.79 | Top3: 90.11 | Top5: 96.72
Epoch 74 | Train Loss: 1.1421 | Top1: 59.84 | Top2: 81.76 | Top3: 90.11 | Top5: 96.75
Epoch 75 | Train Loss: 1.1409 | Top1: 59.78 | Top2: 81.76 | Top3: 90.22 | Top5: 96.72
Epoch 76 | Train Loss: 1.1409 | Top1: 59.84 | Top2: 81.76 | Top3: 90.22 | Top5: 96.75
Epoch 77 | Train Loss: 1.1404 | Top1: 59.84 | Top2: 81.82 | Top3: 90.13 | Top5: 96.72
Epoch 78 | Train Loss: 1.1418 | Top1: 59.81 | Top2: 81.82 | Top3: 90.19 | Top5: 96.69
Epoch 79 | Train Loss: 1.1415 | Top1: 59.84 | Top2: 81.73 | Top3: 90.22 | Top5: 96.78
Epoch 80 | Train Loss: 1.1359 | Top1: 59.75 | Top2: 81.79 | Top3: 90.16 | Top5: 96.75
Epoch 81 | Train Loss: 1.1430 | Top1: 59.69 | Top2: 81.79 | Top3: 90.11 | Top5: 96.75
Epoch 82 | Train Loss: 1.1333 | Top1: 59.75 | Top2: 81.82 | Top3: 90.11 | Top5: 96.75
Epoch 83 | Train Loss: 1.1397 | Top1: 59.72 | Top2: 81.76 | Top3: 90.11 | Top5: 96.75
Epoch 84 | Train Loss: 1.1448 | Top1: 59.78 | Top2: 81.76 | Top3: 90.11 | Top5: 96.72
Epoch 85 | Train Loss: 1.1428 | Top1: 59.84 | Top2: 81.76 | Top3: 90.11 | Top5: 96.72
Epoch 86 | Train Loss: 1.1476 | Top1: 59.87 | Top2: 81.79 | Top3: 90.11 | Top5: 96.72
Epoch 87 | Train Loss: 1.1451 | Top1: 59.92 | Top2: 81.85 | Top3: 90.13 | Top5: 96.75
Epoch 88 | Train Loss: 1.1413 | Top1: 59.81 | Top2: 81.76 | Top3: 90.08 | Top5: 96.78
Epoch 89 | Train Loss: 1.1443 | Top1: 59.95 | Top2: 81.76 | Top3: 90.16 | Top5: 96.75
Saved best model
Epoch 90 | Train Loss: 1.1418 | Top1: 59.89 | Top2: 81.82 | Top3: 90.16 | Top5: 96.75
Epoch 91 | Train Loss: 1.1408 | Top1: 59.89 | Top2: 81.85 | Top3: 90.13 | Top5: 96.72
Epoch 92 | Train Loss: 1.1449 | Top1: 59.87 | Top2: 81.79 | Top3: 90.11 | Top5: 96.75
Epoch 93 | Train Loss: 1.1423 | Top1: 59.98 | Top2: 81.79 | Top3: 90.11 | Top5: 96.75
Saved best model
Epoch 94 | Train Loss: 1.1370 | Top1: 60.01 | Top2: 81.76 | Top3: 90.05 | Top5: 96.75
Saved best model
Epoch 95 | Train Loss: 1.1409 | Top1: 59.92 | Top2: 81.82 | Top3: 90.08 | Top5: 96.78
Epoch 96 | Train Loss: 1.1429 | Top1: 60.01 | Top2: 81.82 | Top3: 90.05 | Top5: 96.75
Epoch 97 | Train Loss: 1.1502 | Top1: 59.95 | Top2: 81.79 | Top3: 90.05 | Top5: 96.75
Epoch 98 | Train Loss: 1.1393 | Top1: 59.98 | Top2: 81.76 | Top3: 90.02 | Top5: 96.75
Epoch 99 | Train Loss: 1.1421 | Top1: 60.04 | Top2: 81.79 | Top3: 90.05 | Top5: 96.75
Saved best model
Epoch 100 | Train Loss: 1.1355 | Top1: 60.01 | Top2: 81.79 | Top3: 90.05 | Top5: 96.75
ann Test metrics: {'top1': 56.540825285338016, 'top2': 81.29938542581212, 'top3': 90.95697980684811, 'top5': 97.01492537313433}

================================================================================
Training Position Model: ann_attention
================================================================================

AttributeError: module 'torch.nn' has no attribute 'GeLU'

In [67]:
pos_results_df = pd.DataFrame(pos_results)
pos_results_df = pos_results_df.sort_values(by="Top-1", ascending=False).reset_index(drop=True)
pos_results_df

           Model      Top-1      Top-2      Top-3      Top-5
0           mlp4  58.560140  80.158033  90.869183  97.366111
1            rnn  58.208955  81.913960  90.869183  97.366111
2            ann  57.418788  80.772608  90.693591  96.927129
3  ann_attention  55.838455  80.509219  90.079017  97.102722
4           lstm  53.731343  79.455663  89.201054  96.488147

In [68]:
print("Feature columns:", feature_cols)
print("Label column:", label_col)

print("Feature sample:")
print(train_pos_df[feature_cols].head())

print("Label sample:")
print(train_pos_df[label_col].head())

print("Label unique count:", train_pos_df[label_col].nunique())
print("Label min:", train_pos_df[label_col].min())
print("Label max:", train_pos_df[label_col].max())

Feature columns: ['pos_x', 'pos_y', 'distance', 'sin_angle', 'cos_angle', 'pos_x2', 'pos_y2', 'pos_xy']
Label column: unit1_beam
Feature sample:
      pos_x     pos_y  distance  sin_angle  cos_angle    pos_x2    pos_y2  \
0  0.809288  0.521084  0.962536   0.541365   0.840787  0.654948  0.271528
1  0.481628  0.294345  0.564450   0.521472   0.853268  0.231965  0.086639
2  0.220279  0.413660  0.468654   0.882654   0.470023  0.048523  0.171114
3  0.214123  0.454721  0.502613   0.904714   0.426019  0.045849  0.206772
4  0.145006  0.409788  0.434688   0.942719   0.333588  0.021027  0.167927

     pos_xy
0  0.421707
1  0.141765
2  0.091120
3  0.097366
4  0.059422
Label sample:
0    17
1    14
2    17
3    20
4    17
Name: unit1_beam, dtype: int64
Label unique count: 29
Label min: 2
Label max: 30

checking

In [93]:
"/content/drive/MyDrive/best_position_mlp4.pth"
"/content/drive/MyDrive/best_position_rnn.pth"
"/content/drive/MyDrive/best_position_lstm.pth"

'/content/drive/MyDrive/best_position_lstm.pth'

In [94]:
import os
import torch

ensemble_model_names = ["mlp4", "rnn", "lstm"]

ensemble_models = []

for model_name in ensemble_model_names:
    ckpt_path = f"/content/drive/MyDrive/best_position_{model_name}.pth"
    print(model_name, os.path.exists(ckpt_path), ckpt_path)

    model = build_position_model(
        model_name,
        input_dim=input_dim,
        num_classes=num_classes_pos
    )

    model.load_state_dict(torch.load(ckpt_path, map_location=device))
    model = model.to(device)
    model.eval()

    ensemble_models.append(model)

mlp4 True /content/drive/MyDrive/best_position_mlp4.pth

RuntimeError: Error(s) in loading state_dict for FourLayerMLP:
	size mismatch for net.0.weight: copying a param with shape torch.Size([128, 8]) from checkpoint, the shape in current model is torch.Size([512, 14]).
	size mismatch for net.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for net.1.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for net.1.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for net.1.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for net.1.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for net.4.weight: copying a param with shape torch.Size([256, 128]) from checkpoint, the shape in current model is torch.Size([256, 512]).

In [91]:
print("hello world ")

hello world

In [92]:
import os
import torch

ensemble_model_names = ["mlp4", "rnn", "lstm"]

ensemble_models = []

for model_name in ensemble_model_names:
    ckpt_path = f"/content/drive/MyDrive/best_position_{model_name}.pth"

    print(model_name, os.path.exists(ckpt_path), ckpt_path)

    model = build_position_model(
        model_name,
        input_dim=input_dim,
        num_classes=num_classes_pos
    )

    model.load_state_dict(torch.load(ckpt_path, map_location=device))
    model = model.to(device)
    model.eval()

    ensemble_models.append(model)

print("Loaded ensemble models:", len(ensemble_models))

mlp4 True /content/drive/MyDrive/best_position_mlp4.pth

RuntimeError: Error(s) in loading state_dict for FourLayerMLP:
	size mismatch for net.0.weight: copying a param with shape torch.Size([128, 8]) from checkpoint, the shape in current model is torch.Size([512, 14]).
	size mismatch for net.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for net.1.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for net.1.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for net.1.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for net.1.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for net.4.weight: copying a param with shape torch.Size([256, 128]) from checkpoint, the shape in current model is torch.Size([256, 512]).